using Essenthos.Core.Macula;
using FluentAssertions;
using Xunit;

namespace Essenthos.Core.Tests;

/// <summary>
/// MACULA's word table, read: the address, the columns found by name, and the two shapes of file
/// that have to stop the load rather than be read past.
/// </summary>
public sealed class MaculaTests
{
    /// <summary>
    /// The first words of Matthew, with the columns in the order the upstream query writes them.
    /// The fourth row is Ἀβραάμ, which is the row this whole dataset was fetched for: a noun whose
    /// type is <c>proper</c> and not <c>common</c>.
    /// </summary>
    private const string Matthew =
        "xml:id\tref\trole\tclass\ttype\tenglish\tmandarin\tgloss\ttext\tafter\tlemma\tnormalized\t" +
        "strong\tmorph\tperson\tnumber\tgender\tcase\ttense\tvoice\tmood\tdegree\tdomain\tln\t" +
        "frame\tsubjref\treferent\n" +
        "n40001001001\tMAT 1:1!1\t\tnoun\tcommon\t\t\t[The] book\tΒίβλος\t \tβίβλος\tΒίβλος\t976\t" +
        "N-NSF\t\tsingular\tfeminine\tnominative\t\t\t\t\t033005\t33.38\t\t\t\n" +
        "n40001001008\tMAT 1:1!8\t\tnoun\tproper\t\t\tof Abraham\tἈβραάμ\t.\tἈβραάμ\tἈβραάμ\t11\t" +
        "N-PRI\t\t\t\tgenitive\t\t\t\t\t\t\t\t\t\n" +
        "n40001002008\tMAT 1:2!8\tv\tverb\t\t\t\tbegat\tἐγέννησεν\t \tγεννάω\tἐγέννησεν\t1080\t" +
        "V-AAI-3S\tthird\tsingular\t\t\taorist\tactive\tindicative\t\t\t\t\t\t\n";

    [Fact]
    public void ReadsTheAddressAsABookOrdinalChapterVerseAndPosition()
    {
        var words = MaculaReader.Read(Matthew);

        words.Should().HaveCount(3);
        words[0].Book.Should().Be(40, "Matthew is the fortieth book of the canon");
        words[0].Chapter.Should().Be(1);
        words[0].Verse.Should().Be(1);
        words[0].Position.Should().Be(1);
        words[2].Verse.Should().Be(2);
        words[2].Position.Should().Be(8);
    }

    /// <summary>
    /// The field nothing else in the corpus states. Nestle's own morphology calls both of these
    /// words <c>noun</c> and stops there.
    /// </summary>
    [Fact]
    public void ReadsTheStatedNominalType()
    {
        var words = MaculaReader.Read(Matthew);

        words[0].Type.Should().Be("common");
        words[1].Type.Should().Be("proper");
        words[2].Type.Should().BeNull("a verb has no nominal type, and the cell is empty");
    }

    [Fact]
    public void ReadsTheFeaturesAndTheCodeTheyWereReadFrom()
    {
        var verb = MaculaReader.Read(Matthew)[2];

        verb.Class.Should().Be("verb");
        verb.Morph.Should().Be("V-AAI-3S");
        verb.Tense.Should().Be("aorist");
        verb.Voice.Should().Be("active");
        verb.Mood.Should().Be("indicative");
        verb.Person.Should().Be("third");
        verb.Case.Should().BeNull();
        verb.Lemma.Should().Be("γεννάω");
    }

    /// <summary>
    /// The file is generated by a query over trees that gain attributes as the project adds
    /// datasets, so a column can be inserted anywhere. Reading by position would take the semantic
    /// domain for the mood and say nothing about it.
    /// </summary>
    [Fact]
    public void FindsItsColumnsByNameRatherThanByPosition()
    {
        var moved = "ref\ttype\tclass\ttext\tlemma\tmorph\tcase\tfuture-column\n" +
                    "MAT 1:1!8\tproper\tnoun\tἈβραάμ\tἈβραάμ\tN-PRI\tgenitive\tanything\n";

        var word = MaculaReader.Read(moved).Should().ContainSingle().Which;

        word.Type.Should().Be("proper");
        word.Class.Should().Be("noun");
        word.Case.Should().Be("genitive");
    }

    [Fact]
    public void StopsWhenAColumnTheLoaderReadsIsGone()
    {
        var without = "ref\tclass\tlemma\tmorph\tcase\ttext\n" + "MAT 1:1!1\tnoun\tβίβλος\tN-NSF\tnominative\tΒίβλος\n";

        var thrown = () => MaculaReader.Read(without);

        thrown.Should().Throw<InvalidDataException>().WithMessage("*type*");
    }

    /// <summary>
    /// MACULA Greek is the New Testament. A book code outside it means the file being read is some
    /// other table, and reading it would put annotations on words in another testament.
    /// </summary>
    [Fact]
    public void StopsOnABookThisDatasetDoesNotCover()
    {
        var elsewhere = "ref\tclass\ttype\tlemma\tmorph\tcase\ttext\n" +
                        "GEN 1:1!1\tnoun\tcommon\tἀρχή\tN-DSF\tdative\tἀρχῇ\n";

        var thrown = () => MaculaReader.Read(elsewhere);

        thrown.Should().Throw<InvalidDataException>().WithMessage("*GEN*");
    }

    [Fact]
    public void StopsOnAnAddressThatIsNotOne()
    {
        var wrong = "ref\tclass\ttype\tlemma\tmorph\tcase\ttext\n" +
                    "n40001001001\tnoun\tcommon\tβίβλος\tN-NSF\tnominative\tΒίβλος\n";

        var thrown = () => MaculaReader.Read(wrong);

        thrown.Should().Throw<InvalidDataException>().WithMessage("*MAT 1:1!1*");
    }
}
