SELECT ?e ?eLabel ?time ?prec ?kindLabel ?sitelinks ?whereLabel ?whereStart ?whereEnd ?whereHistorical WHERE {
  ?e wikibase:sitelinks ?sitelinks .
  FILTER(?sitelinks >= 14)
  ?e p:P585/psv:P585 [ wikibase:timeValue ?time ; wikibase:timePrecision ?prec ] .
  FILTER(?prec >= 9)
  FILTER(?time >= "-3500-01-01T00:00:00Z"^^xsd:dateTime && ?time <= "0110-01-01T00:00:00Z"^^xsd:dateTime)
  ?e wdt:P31 ?kind .
  OPTIONAL {
    ?e p:P17 ?stated .
    ?stated ps:P17 ?where .
    FILTER NOT EXISTS { ?stated wikibase:rank wikibase:DeprecatedRank . }
    OPTIONAL { ?stated pq:P580 ?statedStart . }
    OPTIONAL { ?stated pq:P582 ?statedEnd . }
    OPTIONAL { ?where wdt:P571 ?founded . }
    OPTIONAL { ?where wdt:P576 ?dissolved . }
    BIND(EXISTS { ?where wdt:P31 wd:Q3024240 . } AS ?whereHistorical)
  }
  BIND(COALESCE(?statedStart, ?founded) AS ?whereStart)
  BIND(COALESCE(?statedEnd, ?dissolved) AS ?whereEnd)
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
