using System.Text.Json.Serialization;
using Essenthos.Core.Endpoints;

namespace Essenthos.Core;

/// <summary>
/// Every record any endpoint returns is registered here, including its list and array forms. A
/// record that is missing fails at runtime on first request rather than at compile time.
/// </summary>
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(DatasetCountsResponse))]
[JsonSerializable(typeof(VerificationResponse))]
[JsonSerializable(typeof(VerificationReportResponse))]
[JsonSerializable(typeof(ProblemResponse))]
[JsonSerializable(typeof(SyntaxGroupResponse))]
[JsonSerializable(typeof(SyntaxWordResponse))]
[JsonSerializable(typeof(SyntaxListResponse))]
[JsonSerializable(typeof(IList<SyntaxGroupResponse>))]
[JsonSerializable(typeof(IList<SyntaxWordResponse>))]
[JsonSerializable(typeof(List<SyntaxGroupResponse>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(StrongEntryResponse))]
[JsonSerializable(typeof(StrongListResponse))]
[JsonSerializable(typeof(StrongOccurrenceResponse))]
[JsonSerializable(typeof(StrongOccurrenceListResponse))]
[JsonSerializable(typeof(IList<StrongEntryResponse>))]
[JsonSerializable(typeof(IList<StrongOccurrenceResponse>))]
[JsonSerializable(typeof(CanonResponse))]
[JsonSerializable(typeof(CanonSectionResponse))]
[JsonSerializable(typeof(CanonListResponse))]
[JsonSerializable(typeof(IList<CanonResponse>))]
[JsonSerializable(typeof(IList<CanonSectionResponse>))]
[JsonSerializable(typeof(EntityListResponse))]
[JsonSerializable(typeof(EntitySummaryResponse))]
[JsonSerializable(typeof(EntityResponse))]
[JsonSerializable(typeof(EntityNameResponse))]
[JsonSerializable(typeof(EntityRelationshipResponse))]
[JsonSerializable(typeof(EntityReferenceResponse))]
[JsonSerializable(typeof(EntityReferenceListResponse))]
[JsonSerializable(typeof(EntityNamingResponse))]
[JsonSerializable(typeof(IList<EntityNamingResponse>))]
[JsonSerializable(typeof(EventResponse))]
[JsonSerializable(typeof(EventListResponse))]
[JsonSerializable(typeof(TimelineResponse))]
[JsonSerializable(typeof(TimelineEventResponse))]
[JsonSerializable(typeof(IList<TimelineEventResponse>))]
[JsonSerializable(typeof(IList<EntitySummaryResponse>))]
[JsonSerializable(typeof(IList<EntityNameResponse>))]
[JsonSerializable(typeof(IList<EntityRelationshipResponse>))]
[JsonSerializable(typeof(IList<EntityReferenceResponse>))]
[JsonSerializable(typeof(IList<EventResponse>))]
[JsonSerializable(typeof(SearchResultsResponse))]
[JsonSerializable(typeof(SearchHitResponse))]
[JsonSerializable(typeof(SearchTermResponse))]
[JsonSerializable(typeof(IList<SearchHitResponse>))]
[JsonSerializable(typeof(IList<SearchTermResponse>))]
[JsonSerializable(typeof(WordDetailResponse))]
[JsonSerializable(typeof(WordRenderingResponse))]
[JsonSerializable(typeof(IList<WordRenderingResponse>))]
[JsonSerializable(typeof(StrongRenderingsResponse))]
[JsonSerializable(typeof(StrongRenderingResponse))]
[JsonSerializable(typeof(IList<StrongRenderingResponse>))]
[JsonSerializable(typeof(IList<string>))]
[JsonSerializable(typeof(IReadOnlyList<string>))]
[JsonSerializable(typeof(CorpusListResponse))]
[JsonSerializable(typeof(CorpusResponse))]
[JsonSerializable(typeof(IList<CorpusResponse>))]
[JsonSerializable(typeof(List<CorpusResponse>))]
[JsonSerializable(typeof(CoverageResponse))]
[JsonSerializable(typeof(BookListResponse))]
[JsonSerializable(typeof(BookResponse))]
[JsonSerializable(typeof(IList<BookResponse>))]
[JsonSerializable(typeof(List<BookResponse>))]
[JsonSerializable(typeof(BookRefResponse))]
[JsonSerializable(typeof(VerseRefResponse))]
[JsonSerializable(typeof(MorphologyResponse))]
[JsonSerializable(typeof(EntityRefResponse))]
[JsonSerializable(typeof(TextWordResponse))]
[JsonSerializable(typeof(IList<TextWordResponse>))]
[JsonSerializable(typeof(List<TextWordResponse>))]
[JsonSerializable(typeof(TextVerseResponse))]
[JsonSerializable(typeof(IList<TextVerseResponse>))]
[JsonSerializable(typeof(List<TextVerseResponse>))]
[JsonSerializable(typeof(ChapterTextResponse))]
[JsonSerializable(typeof(ParallelCellResponse))]
[JsonSerializable(typeof(ParallelVerseResponse))]
[JsonSerializable(typeof(IList<ParallelVerseResponse>))]
[JsonSerializable(typeof(List<ParallelVerseResponse>))]
[JsonSerializable(typeof(DatasetListResponse))]
[JsonSerializable(typeof(DatasetResponse))]
[JsonSerializable(typeof(IList<DatasetResponse>))]
[JsonSerializable(typeof(List<DatasetResponse>))]
[JsonSerializable(typeof(DatasetCounts))]
[JsonSerializable(typeof(WorkResponse))]
[JsonSerializable(typeof(IList<WorkResponse>))]
[JsonSerializable(typeof(List<WorkResponse>))]
[JsonSerializable(typeof(UndeclaredResponse))]
[JsonSerializable(typeof(IList<UndeclaredResponse>))]
[JsonSerializable(typeof(List<UndeclaredResponse>))]
[JsonSerializable(typeof(ParallelTextResponse))]
[JsonSerializable(typeof(Dictionary<string, ParallelCellResponse?>))]
internal partial class AppJsonSerializerContext : JsonSerializerContext;
