// <auto-generated />
using System;
using System.Collections.Generic;
using Essenthos.Core.Accounts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Essenthos.Core.Accounts.Migrations
{
    [DbContext(typeof(AccountsDbContext))]
    [Migration("20260926204956_ChapterBookmarks")]
    partial class ChapterBookmarks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("revision");

            modelBuilder.Entity("Essenthos.Core.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("About")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("about");

                    b.Property<bool>("Admin")
                        .HasColumnType("boolean")
                        .HasColumnName("admin");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("display_name");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<int>("PhotoVersion")
                        .HasColumnType("integer")
                        .HasColumnName("photo_version");

                    b.Property<string>("ProviderPhotoUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("provider_photo_url");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("Revision")
                        .HasDatabaseName("ix_account_revision");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.AccountEmail", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Email")
                        .HasName("pk_account_email");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_account_email_account_id");

                    b.ToTable("account_email", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.AccountPhoto", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId")
                        .HasName("pk_account_photo");

                    b.ToTable("account_photo", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.AdminAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("AccountName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("account_name");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("actor_name");

                    b.Property<string>("After")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("after");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Before")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("before");

                    b.Property<Guid?>("SuggestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggestion_id");

                    b.HasKey("Id")
                        .HasName("pk_admin_action");

                    b.HasIndex("At")
                        .HasDatabaseName("ix_admin_action_at");

                    b.HasIndex("AccountId", "At")
                        .HasDatabaseName("ix_admin_action_account_id_at");

                    b.HasIndex("SuggestionId", "At")
                        .HasDatabaseName("ix_admin_action_suggestion_id_at");

                    b.ToTable("admin_action", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.Bookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("Book")
                        .HasColumnType("integer")
                        .HasColumnName("book");

                    b.Property<int>("Chapter")
                        .HasColumnType("integer")
                        .HasColumnName("chapter");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("color");

                    b.Property<string>("Comment")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EndChapter")
                        .HasColumnType("integer")
                        .HasColumnName("end_chapter");

                    b.Property<int>("EndVerse")
                        .HasColumnType("integer")
                        .HasColumnName("end_verse");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Text")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Verse")
                        .HasColumnType("integer")
                        .HasColumnName("verse");

                    b.HasKey("Id")
                        .HasName("pk_bookmark");

                    b.HasIndex("Revision")
                        .HasDatabaseName("ix_bookmark_revision");

                    b.HasIndex("AccountId", "Book", "Chapter")
                        .HasDatabaseName("ix_bookmark_account_id_book_chapter");

                    b.ToTable("bookmark", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.ChapterBookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("Book")
                        .HasColumnType("integer")
                        .HasColumnName("book");

                    b.Property<int>("Chapter")
                        .HasColumnType("integer")
                        .HasColumnName("chapter");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.PrimitiveCollection<List<string>>("Texts")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("texts");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Verse")
                        .HasColumnType("integer")
                        .HasColumnName("verse");

                    b.HasKey("Id")
                        .HasName("pk_chapter_bookmark");

                    b.HasIndex("Revision")
                        .HasDatabaseName("ix_chapter_bookmark_revision");

                    b.HasIndex("AccountId", "Book", "Chapter")
                        .IsUnique()
                        .HasDatabaseName("ix_chapter_bookmark_account_id_book_chapter");

                    b.ToTable("chapter_bookmark", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.Credential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_credential");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_credential_account_id");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_credential_provider_subject");

                    b.ToTable("credential", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_key");

                    b.ToTable("data_protection_key", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("browser");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("os");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<DateTimeOffset?>("SettingsChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settings_changed_at");

                    b.Property<DateTimeOffset?>("SignedOutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_out_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_device");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_device_account_id");

                    b.HasIndex("Revision")
                        .HasDatabaseName("ix_device_revision");

                    b.ToTable("device", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.Reading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Book")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("book");

                    b.Property<int>("Chapter")
                        .HasColumnType("integer")
                        .HasColumnName("chapter");

                    b.Property<string>("Corpora")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("corpora");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.HasKey("Id")
                        .HasName("pk_reading");

                    b.HasIndex("AccountId", "At")
                        .HasDatabaseName("ix_reading_account_id_at");

                    b.HasIndex("DeviceId", "At")
                        .HasDatabaseName("ix_reading_device_id_at");

                    b.ToTable("reading", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Device")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_session");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_session_account_id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_session_device_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_session_token_hash");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.Suggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<DateTimeOffset>("AuthorSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("author_seen_at");

                    b.Property<string>("Body")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("body");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Fields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("fields");

                    b.Property<bool>("HasLink")
                        .HasColumnType("boolean")
                        .HasColumnName("has_link");

                    b.Property<string>("Language")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("language");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<DateTimeOffset?>("LastReplyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reply_at");

                    b.PrimitiveCollection<List<string>>("Links")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("links");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<string>("Search")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_suggestion");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("ix_suggestion_assigned_to");

                    b.HasIndex("AccountId", "CreatedAt")
                        .HasDatabaseName("ix_suggestion_account_id_created_at");

                    b.HasIndex("Status", "LastActivityAt")
                        .HasDatabaseName("ix_suggestion_status_last_activity_at");

                    b.ToTable("suggestion", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.SuggestionMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("body");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<Guid>("SuggestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggestion_id");

                    b.HasKey("Id")
                        .HasName("pk_suggestion_message");

                    b.HasIndex("AuthorId", "At")
                        .HasDatabaseName("ix_suggestion_message_author_id_at");

                    b.HasIndex("SuggestionId", "At")
                        .HasDatabaseName("ix_suggestion_message_suggestion_id_at");

                    b.ToTable("suggestion_message", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.AccountEmail", b =>
                {
                    b.HasOne("Essenthos.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_email_account_account_id");
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.AccountPhoto", b =>
                {
                    b.HasOne("Essenthos.Core.Accounts.Account", null)
                        .WithOne()
                        .HasForeignKey("Essenthos.Core.Accounts.AccountPhoto", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_photo_account_account_id");
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.Bookmark", b =>
                {
                    b.HasOne("Essenthos.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookmark_account_account_id");
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.ChapterBookmark", b =>
                {
                    b.HasOne("Essenthos.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chapter_bookmark_account_account_id");
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.Credential", b =>
                {
                    b.HasOne("Essenthos.Core.Accounts.Account", "Account")
                        .WithMany("Credentials")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credential_account_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.Device", b =>
                {
                    b.HasOne("Essenthos.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_account_account_id");
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.Reading", b =>
                {
                    b.HasOne("Essenthos.Core.Accounts.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_device_device_id");
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.Session", b =>
                {
                    b.HasOne("Essenthos.Core.Accounts.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_account_account_id");

                    b.HasOne("Essenthos.Core.Accounts.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_session_devices_device_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.Suggestion", b =>
                {
                    b.HasOne("Essenthos.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suggestion_account_account_id");

                    b.HasOne("Essenthos.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_suggestion_account_assigned_to");
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.SuggestionMessage", b =>
                {
                    b.HasOne("Essenthos.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_suggestion_message_account_author_id");

                    b.HasOne("Essenthos.Core.Accounts.Suggestion", null)
                        .WithMany()
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suggestion_message_suggestion_suggestion_id");
                });

            modelBuilder.Entity("Essenthos.Core.Accounts.Account", b =>
                {
                    b.Navigation("Credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
