using Essenthos.Core.Corpus;

namespace Essenthos.Core.Endpoints;

/// <summary>
/// What each text is, in a sentence or two, in every language the interface speaks.
///
/// Each one restates the text's own About paragraph and rights note, which are the corpus's record
/// and stay in English; nothing here says what those do not. They are the lead of a text's page,
/// written for somebody who has never heard of the edition, and the About is quoted in full beneath.
///
/// Keyed by the identifier the text had when this was written. A text renamed since keeps its old
/// identifier as an alias, and <see cref="For"/> looks there too, so a rename does not silence it.
/// </summary>
internal static class TextSummaries
{
    private static readonly Dictionary<string, IReadOnlyDictionary<string, string>> Written =
        new(StringComparer.OrdinalIgnoreCase)
        {
            ["BHSA"] = Say(
                "The Hebrew Bible as the Leningrad Codex preserves it — the Masoretic text of the Biblia Hebraica Stuttgartensia — with the linguistic annotation the ETCBC in Amsterdam has built since the 1970s: parts of speech, verb stems, and the clause and phrase structure of every verse.",
                "Єврейська Біблія в тому вигляді, в якому її зберіг Ленінградський кодекс, — масоретський текст Biblia Hebraica Stuttgartensia — з лінгвістичною розміткою, яку амстердамський ETCBC будує з 1970-х років: частини мови, породи дієслів, будова речень і словосполучень кожного вірша.",
                "Die Hebräische Bibel, wie der Codex Leningradensis sie bewahrt – der masoretische Text der Biblia Hebraica Stuttgartensia – mit der sprachlichen Annotation, die das ETCBC in Amsterdam seit den 1970er-Jahren aufbaut: Wortarten, Verbalstämme und die Satz- und Phrasenstruktur jedes Verses.",
                "La Biblia hebrea tal como la conserva el Códice de Leningrado —el texto masorético de la Biblia Hebraica Stuttgartensia— con la anotación lingüística que el ETCBC de Ámsterdam construye desde los años setenta: categorías gramaticales, temas verbales y la estructura de cláusulas y sintagmas de cada versículo."),
            ["SP"] = Say(
                "The Torah as the Samaritan community has transmitted it — a third Hebrew textual family beside the Masoretic text and the Qumran scrolls. Stefan Schorch's critical edition from Halle, transcribed from two manuscripts and written without vowel points, as the Samaritan tradition writes it.",
                "Тора в тому вигляді, в якому її передала самарянська громада, — третя гілка єврейського тексту поряд із масоретським текстом і кумранськими сувоями. Критичне видання Штефана Шорха (Галле), переписане з двох рукописів без огласовок, як і пише самарянська традиція.",
                "Die Tora, wie die samaritanische Gemeinde sie überliefert hat – eine dritte hebräische Textfamilie neben dem masoretischen Text und den Qumranrollen. Stefan Schorchs kritische Ausgabe aus Halle, nach zwei Handschriften transkribiert und ohne Vokalzeichen, wie die samaritanische Tradition schreibt.",
                "La Torá tal como la ha transmitido la comunidad samaritana: una tercera familia textual hebrea junto al texto masorético y los rollos de Qumrán. Edición crítica de Stefan Schorch (Halle), transcrita de dos manuscritos y sin puntos vocálicos, como escribe la tradición samaritana."),
            ["GEEZ81"] = Say(
                "The Bible of the Ethiopian Orthodox Tewahedo Church in Ge'ez, its ancient liturgical language: all eighty-one books the church counts, among them 1 Enoch and Jubilees, which survive whole only in Ge'ez. Its Old Testament was translated from the Greek Septuagint in the fourth to sixth centuries, so it is a witness to the Greek Bible. Most books are a digital transcription of the church's printed Bible made by hand, with typing errors; Genesis to 2 Kings, the Psalms, Wisdom and 4 Baruch come from Dillmann's and Ludolf's older editions.",
                "Біблія Ефіопської православної церкви Тевахедо мовою ґеез, її давньою богослужбовою мовою: усі вісімдесят одна книга, які визнає церква, серед них 1 Єноха та Книга Ювілеїв, що повністю збереглися лише ґеезом. Старий Заповіт перекладено з грецької Септуагінти в IV–VI століттях, тож це свідок грецької Біблії. Більшість книг — цифровий передрук друкованої Біблії церкви, набраний вручну, з помилками набору; від Буття до 2 Царів, Псалми, Книга Премудрості та 4 Варуха взяті зі старших видань Дільмана й Лудольфа.",
                "Die Bibel der Äthiopisch-Orthodoxen Tewahedo-Kirche in Ge'ez, ihrer alten Liturgiesprache: alle einundachtzig Bücher, die die Kirche zählt, darunter 1 Henoch und das Jubiläenbuch, die vollständig nur auf Ge'ez erhalten sind. Das Alte Testament wurde im 4. bis 6. Jahrhundert aus der griechischen Septuaginta übersetzt und ist daher ein Zeuge der griechischen Bibel. Die meisten Bücher sind eine von Hand angefertigte digitale Abschrift der gedruckten Bibel der Kirche, mit Tippfehlern; Genesis bis 2 Könige, die Psalmen, die Weisheit und 4 Baruch stammen aus den älteren Ausgaben von Dillmann und Ludolf.",
                "La Biblia de la Iglesia Ortodoxa Etíope Tewahedo en ge'ez, su antigua lengua litúrgica: los ochenta y un libros que cuenta la Iglesia, entre ellos 1 Enoc y Jubileos, que solo se conservan completos en ge'ez. Su Antiguo Testamento se tradujo de la Septuaginta griega entre los siglos IV y VI, por lo que es un testigo de la Biblia griega. La mayoría de los libros son una transcripción digital hecha a mano de la Biblia impresa de la Iglesia, con errores de tecleo; de Génesis a 2 Reyes, los Salmos, Sabiduría y 4 Baruc proceden de las ediciones más antiguas de Dillmann y Ludolf."),
            ["NESTLE1904"] = Say(
                "The Greek New Testament Eberhard Nestle built by combining the printed editions of Tischendorf, Westcott and Hort, and Weymouth, in the British and Foreign Bible Society's printing of 1904 — close to the modern critical text without being one. The digital edition carries full morphology.",
                "Грецький Новий Заповіт, який Еберхард Нестле склав, поєднавши друковані видання Тішендорфа, Весткотта й Горта та Веймута, у виданні Британського і закордонного біблійного товариства 1904 року — близький до сучасного критичного тексту, але не тотожний йому. Цифрове видання має повну морфологічну розмітку.",
                "Das griechische Neue Testament, das Eberhard Nestle aus den gedruckten Ausgaben von Tischendorf, Westcott und Hort sowie Weymouth zusammensetzte, im Druck der Britischen und Ausländischen Bibelgesellschaft von 1904 – nahe am modernen kritischen Text, ohne einer zu sein. Die digitale Ausgabe ist vollständig morphologisch annotiert.",
                "El Nuevo Testamento griego que Eberhard Nestle compuso combinando las ediciones impresas de Tischendorf, Westcott y Hort, y Weymouth, en la impresión de la Sociedad Bíblica Británica y Extranjera de 1904: cercano al texto crítico moderno sin serlo. La edición digital lleva morfología completa."),
            ["TISCH"] = Say(
                "Tischendorf's eighth critical edition of the Greek New Testament (1869–1872), where he weighed the Codex Sinaiticus he had found at Saint Catherine's. One of the three editions Nestle 1904 takes its majority from; the text is served without its apparatus.",
                "Восьме критичне видання грецького Нового Заповіту Тішендорфа (1869–1872), у якому він зважив знайдений ним у монастирі Святої Катерини Синайський кодекс. Одне з трьох видань, за більшістю яких укладено текст Нестле 1904; подано без критичного апарату.",
                "Tischendorfs achte kritische Ausgabe des griechischen Neuen Testaments (1869–1872), in der er den von ihm im Katharinenkloster gefundenen Codex Sinaiticus gewichtete. Eine der drei Ausgaben, aus deren Mehrheit Nestle 1904 gebildet ist; der Text steht hier ohne Apparat.",
                "La octava edición crítica del Nuevo Testamento griego de Tischendorf (1869–1872), en la que sopesó el Códice Sinaítico que él mismo había hallado en Santa Catalina. Una de las tres ediciones cuya mayoría sigue Nestle 1904; el texto se ofrece sin su aparato."),
            ["WH1881"] = Say(
                "The Greek New Testament of Westcott and Hort (1881), who weighed manuscripts by family and trusted Codex Vaticanus and Codex Sinaiticus above the rest — the edition that ended the Received Text's reign in scholarship, and another of Nestle's three sources. This transcription has no accents or breathings.",
                "Грецький Новий Заповіт Весткотта й Горта (1881). Вони зважували рукописи за родинами й найбільше довіряли Ватиканському та Синайському кодексам; це видання поклало край пануванню Textus Receptus у науці й стало ще одним із трьох джерел Нестле. Ця транскрипція не має наголосів і придихів.",
                "Das griechische Neue Testament von Westcott und Hort (1881), die Handschriften nach Familien gewichteten und dem Codex Vaticanus und dem Codex Sinaiticus am meisten vertrauten – die Ausgabe, die die Herrschaft des Textus receptus in der Wissenschaft beendete, und eine weitere von Nestles drei Quellen. Diese Transkription hat keine Akzente und Spiritus.",
                "El Nuevo Testamento griego de Westcott y Hort (1881), que valoraron los manuscritos por familias y confiaron sobre todo en los códices Vaticano y Sinaítico: la edición que acabó con el reinado del Texto Recibido en la erudición, y otra de las tres fuentes de Nestle. Esta transcripción no lleva acentos ni espíritus."),
            ["TR1894"] = Say(
                "A reconstruction of the Greek the King James translators followed: Scrivener worked back from the English, choosing at each place the reading of Erasmus, Stephanus or Beza that the Authorised Version had taken. First published in 1881; this is the 1894 printing.",
                "Реконструкція грецького тексту, за яким працювали перекладачі Біблії короля Якова: Скрівенер ішов від англійського тексту назад, обираючи в кожному місці те читання Еразма, Стефана чи Бези, яке прийняла Авторизована версія. Уперше видано 1881 року; тут — друк 1894 року.",
                "Eine Rekonstruktion des griechischen Textes, dem die Übersetzer der King James folgten: Scrivener ging vom Englischen zurück und wählte an jeder Stelle die Lesart von Erasmus, Stephanus oder Beza, der die Authorised Version gefolgt war. Erstmals 1881 erschienen; dies ist der Druck von 1894.",
                "Una reconstrucción del griego que siguieron los traductores de la King James: Scrivener partió del inglés y eligió en cada lugar la lectura de Erasmo, Estéfano o Beza que había adoptado la Versión Autorizada. Publicada por primera vez en 1881; esta es la impresión de 1894."),
            ["TR1550"] = Say(
                "Robert Estienne's Greek New Testament of 1550, the editio regia printed in Paris, resting on Erasmus and the Complutensian Polyglot. In England it became the Received Text, which is why it stands here beside Scrivener: two states of one tradition.",
                "Грецький Новий Заповіт Робера Етьєна 1550 року — «королівське видання», надруковане в Парижі на основі Еразма й Комплютенської поліглоти. В Англії саме воно стало Textus Receptus, тому тут воно стоїть поруч зі Скрівенером: два стани однієї традиції.",
                "Robert Estiennes griechisches Neues Testament von 1550, die in Paris gedruckte Editio regia, gestützt auf Erasmus und die Complutensische Polyglotte. In England wurde es zum Textus receptus – darum steht es hier neben Scrivener: zwei Zustände einer Überlieferung.",
                "El Nuevo Testamento griego de Robert Estienne de 1550, la editio regia impresa en París, basada en Erasmo y en la Políglota Complutense. En Inglaterra se convirtió en el Texto Recibido, por eso está aquí junto a Scrivener: dos estados de una misma tradición."),
            ["RP2018"] = Say(
                "The reading of the majority of surviving Greek manuscripts, as Maurice Robinson and William Pierpont reconstructed it; where the manuscripts divide, the division is printed rather than resolved. First published in 1991; this is the 2018 edition.",
                "Читання більшості збережених грецьких рукописів у реконструкції Моріса Робінсона й Вільяма Пірпонта; де рукописи розходяться, розбіжність надруковано, а не розв'язано. Уперше видано 1991 року; тут — видання 2018 року.",
                "Die Lesart der Mehrheit der erhaltenen griechischen Handschriften, wie Maurice Robinson und William Pierpont sie rekonstruierten; wo die Handschriften auseinandergehen, wird die Spaltung abgedruckt statt entschieden. Erstmals 1991 erschienen; dies ist die Ausgabe von 2018.",
                "La lectura de la mayoría de los manuscritos griegos conservados, tal como la reconstruyeron Maurice Robinson y William Pierpont; donde los manuscritos se dividen, se imprime la división en lugar de resolverla. Publicada por primera vez en 1991; esta es la edición de 2018."),
            ["GRCBRENT"] = Say(
                "The Septuagint — the Greek translation of the Hebrew Scriptures made in Alexandria between roughly the third and the first century BC, by different hands book by book — in the text Sir Lancelot Brenton printed facing his English: the Roman edition of 1587, which follows Codex Vaticanus and fills the codex's gaps from other manuscripts (1844, with the Apocrypha 1851). Its lemmas come from GLAUx.",
                "Септуагінта — грецький переклад єврейського Письма, зроблений в Александрії приблизно між III і I століттями до н. е. різними перекладачами, книга за книгою, — у тексті, який сер Ланселот Брентон надрукував поруч зі своїм англійським перекладом: це римське видання 1587 року, що йде за Ватиканським кодексом, а його прогалини заповнює з інших рукописів (1844, з апокрифами — 1851). Леми взято з GLAUx.",
                "Die Septuaginta – die griechische Übersetzung der hebräischen Schriften, in Alexandria etwa zwischen dem 3. und dem 1. Jahrhundert v. Chr. von verschiedenen Händen Buch für Buch angefertigt – in dem Text, den Sir Lancelot Brenton seiner englischen Übersetzung gegenüberstellte: die römische Ausgabe von 1587, die dem Codex Vaticanus folgt und seine Lücken aus anderen Handschriften füllt (1844, mit den Apokryphen 1851). Die Lemmata stammen aus GLAUx.",
                "La Septuaginta —la traducción griega de las Escrituras hebreas hecha en Alejandría aproximadamente entre los siglos III y I a. C., por distintas manos libro a libro— en el texto que Sir Lancelot Brenton imprimió frente a su traducción inglesa: la edición romana de 1587, que sigue el Códice Vaticano y completa sus lagunas con otros manuscritos (1844; con los apócrifos, 1851). Sus lemas proceden de GLAUx."),
            ["SWETE"] = Say(
                "The Septuagint as Henry Barclay Swete printed it at Cambridge (1887–1894): Codex Vaticanus as it stands, its gaps filled from Sinaiticus and Alexandrinus and the other manuscripts' readings left to the apparatus. The apparatus is not included here, only the text.",
                "Септуагінта у виданні Генрі Барклі Світа (Кембридж, 1887–1894): Ватиканський кодекс як він є, прогалини заповнено за Синайським і Александрійським кодексами, а читання інших рукописів винесено до апарату. Апарату тут немає — лише текст.",
                "Die Septuaginta, wie Henry Barclay Swete sie in Cambridge druckte (1887–1894): der Codex Vaticanus, wie er dasteht, Lücken aus dem Sinaiticus und dem Alexandrinus ergänzt, die Lesarten der übrigen Handschriften im Apparat. Der Apparat ist hier nicht enthalten, nur der Text.",
                "La Septuaginta tal como la imprimió Henry Barclay Swete en Cambridge (1887–1894): el Códice Vaticano tal cual, con sus lagunas completadas con el Sinaítico y el Alejandrino y las lecturas de los demás manuscritos relegadas al aparato. Aquí no está el aparato, solo el texto."),
            ["OTTLEY"] = Say(
                "The Book of Isaiah as Codex Alexandrinus has it — the other great early codex of the Greek Bible, copied in the fifth century — printed as the manuscript stands by Richard Rusden Ottley at Cambridge (1904). It can be read beside Swete's text of Codex Vaticanus word by word. Ottley's notes are not included here, only the text.",
                "Книга Ісаї так, як її подає Александрійський кодекс — другий великий ранній кодекс грецької Біблії, переписаний у V столітті, — надрукована Річардом Расденом Оттлі в Кембриджі (1904) такою, якою вона є в рукописі. Її можна читати поруч із текстом Ватиканського кодексу у виданні Світа, слово за словом. Приміток Оттлі тут немає — лише текст.",
                "Das Buch Jesaja, wie der Codex Alexandrinus es bietet – der andere große frühe Kodex der griechischen Bibel, im 5. Jahrhundert geschrieben –, so abgedruckt, wie die Handschrift dasteht, von Richard Rusden Ottley in Cambridge (1904). Es lässt sich Wort für Wort neben Swetes Text des Codex Vaticanus lesen. Ottleys Anmerkungen sind hier nicht enthalten, nur der Text.",
                "El libro de Isaías tal como lo trae el Códice Alejandrino —el otro gran códice antiguo de la Biblia griega, copiado en el siglo V—, impreso tal cual está en el manuscrito por Richard Rusden Ottley en Cambridge (1904). Puede leerse palabra por palabra junto al texto del Códice Vaticano de Swete. Aquí no están las notas de Ottley, solo el texto."),
            ["KJV"] = Say(
                "The English translation made in 1604–1611 by six companies at Westminster, Oxford and Cambridge from the Hebrew and Greek editions of the day. What is served is the modern standard text with modernised spelling, not the 1611 printing.",
                "Англійський переклад, зроблений у 1604–1611 роках шістьма групами перекладачів у Вестмінстері, Оксфорді й Кембриджі з тогочасних друкованих видань єврейського та грецького текстів. Тут подано сучасний стандартний текст з осучасненим правописом, а не друк 1611 року.",
                "Die englische Übersetzung, die sechs Arbeitsgruppen in Westminster, Oxford und Cambridge 1604–1611 aus den hebräischen und griechischen Ausgaben ihrer Zeit anfertigten. Hier steht der moderne Standardtext mit modernisierter Schreibung, nicht der Druck von 1611.",
                "La traducción inglesa hecha entre 1604 y 1611 por seis equipos en Westminster, Oxford y Cambridge a partir de las ediciones hebreas y griegas de la época. Lo que se ofrece es el texto estándar moderno, con ortografía modernizada, no la impresión de 1611."),
            ["TYN1534"] = Say(
                "William Tyndale's New Testament, the first translated into English from the Greek and the first printed in English, in his own revision of 1534. The King James kept his wording wherever it could; his spelling is kept as he wrote it.",
                "Новий Заповіт Вільяма Тиндейла — перший, перекладений англійською з грецької, і перший, надрукований англійською, у його власній редакції 1534 року. Біблія короля Якова зберегла його формулювання скрізь, де могла; правопис залишено авторський.",
                "William Tyndales Neues Testament, das erste aus dem Griechischen ins Englische übersetzte und das erste auf Englisch gedruckte, in seiner eigenen Überarbeitung von 1534. Die King James behielt seinen Wortlaut, wo immer sie konnte; seine Schreibung ist beibehalten.",
                "El Nuevo Testamento de William Tyndale, el primero traducido al inglés desde el griego y el primero impreso en inglés, en su propia revisión de 1534. La King James conservó su redacción siempre que pudo; se mantiene su ortografía original."),
            ["GNV1599"] = Say(
                "The Bible England read for two generations before the King James, made from the Hebrew and Greek by Protestant exiles at Geneva. First published in 1560; served here in the 1599 edition, in its original spelling and without the marginal notes.",
                "Біблія, яку Англія читала два покоління до Біблії короля Якова; її переклали з єврейської та грецької протестантські вигнанці в Женеві. Уперше видана 1560 року; тут — видання 1599 року в оригінальному правописі, без коментарів на берегах.",
                "Die Bibel, die England zwei Generationen lang vor der King James las, von protestantischen Exilanten in Genf aus dem Hebräischen und Griechischen übersetzt. Erstmals 1560 erschienen; hier in der Ausgabe von 1599, in originaler Schreibung und ohne die Randanmerkungen.",
                "La Biblia que Inglaterra leyó durante dos generaciones antes de la King James, traducida del hebreo y del griego por exiliados protestantes en Ginebra. Publicada por primera vez en 1560; aquí en la edición de 1599, con su ortografía original y sin las notas marginales."),
            ["ASV"] = Say(
                "The American recension of the Revised Version of 1881–1885: the King James line brought onto the Greek critical text of the nineteenth century. It renders the divine name as Jehovah throughout.",
                "Американська редакція Переглянутої версії 1881–1885 років: традиція Біблії короля Якова, перенесена на грецький критичний текст XIX століття. Боже ім'я скрізь передано як «Єгова».",
                "Die amerikanische Rezension der Revised Version von 1881–1885: die King-James-Tradition, übertragen auf den griechischen kritischen Text des 19. Jahrhunderts. Den Gottesnamen gibt sie durchgehend als Jehovah wieder.",
                "La recensión estadounidense de la Revised Version de 1881–1885: la tradición de la King James llevada al texto crítico griego del siglo XIX. Traduce el nombre divino como Jehovah en todo el texto."),
            ["YLT"] = Say(
                "Robert Young's translation, which reproduces the grammar of the Hebrew and Greek rather than replacing it and renders one original word by one English word wherever it can — hard to read, and for that reason the most useful English text here for comparing with the original. The revised edition of 1898; its Greek is the Textus Receptus.",
                "Переклад Роберта Янга, який відтворює граматику єврейського й грецького тексту замість того, щоб її замінювати, і передає одне слово оригіналу одним англійським словом скрізь, де може, — важкий для читання і саме тому найкорисніший тут англійський текст для порівняння з оригіналом. Переглянуте видання 1898 року; грецький текст — Textus Receptus.",
                "Robert Youngs Übersetzung, die die Grammatik des Hebräischen und Griechischen nachbildet, statt sie zu ersetzen, und ein Wort des Originals, wo immer möglich, durch ein und dasselbe englische Wort wiedergibt – schwer zu lesen und gerade darum der nützlichste englische Text hier für den Vergleich mit dem Original. Die überarbeitete Ausgabe von 1898; ihr griechischer Text ist der Textus receptus.",
                "La traducción de Robert Young, que reproduce la gramática del hebreo y del griego en vez de sustituirla y traduce cada palabra del original por una misma palabra inglesa siempre que puede: difícil de leer y, por eso mismo, el texto inglés más útil de aquí para compararlo con el original. Edición revisada de 1898; su griego es el Texto Recibido."),
            ["JPS1917"] = Say(
                "The first English Bible made by Jews for Jews: a board under Max Margolis translated the Masoretic text over a decade and published it in 1917. It has no New Testament; names are transliterated where Christian versions translate them.",
                "Перша англійська Біблія, зроблена юдеями для юдеїв: рада редакторів під керівництвом Макса Марголіса десять років перекладала масоретський текст і видала його 1917 року. Нового Заповіту в ній немає; імена транслітеровано там, де християнські переклади їх перекладають.",
                "Die erste englische Bibel, von Juden für Juden gemacht: Ein Gremium unter Max Margolis übersetzte ein Jahrzehnt lang den masoretischen Text und veröffentlichte ihn 1917. Ein Neues Testament hat sie nicht; Namen werden transkribiert, wo christliche Übersetzungen sie übersetzen.",
                "La primera Biblia inglesa hecha por judíos para judíos: un comité dirigido por Max Margolis tradujo el texto masorético durante una década y la publicó en 1917. No tiene Nuevo Testamento; los nombres se transliteran donde las versiones cristianas los traducen."),
            ["BSB"] = Say(
                "A new English translation, made so that every English word can be traced to the Hebrew or Greek behind it; its translators publish their own word-level tables, and those are what link it to the originals here. Placed in the public domain on 30 April 2023.",
                "Новий англійський переклад, зроблений так, щоб кожне англійське слово можна було простежити до єврейського чи грецького слова, яке воно передає; перекладачі публікують власні пословні таблиці, і саме вони пов'язують його тут з оригіналами. Переданий у суспільне надбання 30 квітня 2023 року.",
                "Eine neue englische Übersetzung, so angelegt, dass sich jedes englische Wort auf das hebräische oder griechische dahinter zurückführen lässt; die Übersetzer veröffentlichen eigene Wort-für-Wort-Tabellen, und diese verbinden sie hier mit den Grundtexten. Am 30. April 2023 gemeinfrei gestellt.",
                "Una traducción inglesa nueva, hecha para que cada palabra inglesa pueda rastrearse hasta la palabra hebrea o griega que traduce; sus traductores publican sus propias tablas palabra por palabra, y son ellas las que aquí la enlazan con los originales. Pasó al dominio público el 30 de abril de 2023."),
            ["WEB"] = Say(
                "A modern English update of the American Standard Version, revised continuously by volunteers and dedicated to the public domain on purpose; its New Testament is conformed in places to the Byzantine Majority Text.",
                "Сучасне англійське оновлення Американської стандартної версії, яке волонтери постійно переглядають і яке свідомо передано в суспільне надбання; його Новий Заповіт місцями узгоджено з візантійським текстом більшості.",
                "Eine moderne englische Überarbeitung der American Standard Version, von Freiwilligen fortlaufend revidiert und bewusst gemeinfrei gestellt; ihr Neues Testament ist stellenweise an den byzantinischen Mehrheitstext angeglichen.",
                "Una actualización moderna al inglés de la American Standard Version, revisada continuamente por voluntarios y dedicada a propósito al dominio público; su Nuevo Testamento se ajusta en algunos lugares al texto bizantino mayoritario."),
            ["BBE"] = Say(
                "The Bible translated from the Hebrew and Greek into Basic English, a vocabulary of about a thousand words, by a committee under S. H. Hooke and published whole by Cambridge University Press in 1965. It says the sense in the simplest words that carry it, so it reads unlike any other English text here; its New Testament follows the critical Greek text.",
                "Біблія, перекладена з єврейської та грецької на Basic English — словник приблизно з тисячі слів — комітетом під керівництвом С. Г. Гука; повністю видана Кембриджським університетським видавництвом 1965 року. Вона передає зміст найпростішими словами, які його несуть, тому звучить не так, як будь-який інший англійський текст тут; її Новий Заповіт іде за грецьким критичним текстом.",
                "Die Bibel, aus dem Hebräischen und Griechischen in Basic English übersetzt – einen Wortschatz von etwa tausend Wörtern –, von einem Ausschuss unter S. H. Hooke; vollständig 1965 bei Cambridge University Press erschienen. Sie sagt den Sinn mit den einfachsten Wörtern, die ihn tragen, und liest sich darum anders als jeder andere englische Text hier; ihr Neues Testament folgt dem kritischen griechischen Text.",
                "La Biblia traducida del hebreo y del griego al Basic English —un vocabulario de unas mil palabras— por un comité dirigido por S. H. Hooke y publicada completa por Cambridge University Press en 1965. Expresa el sentido con las palabras más sencillas que lo sostienen, por lo que se lee distinta de cualquier otro texto inglés de aquí; su Nuevo Testamento sigue el texto crítico griego."),
            ["LUTH1912"] = Say(
                "Martin Luther's German Bible (New Testament 1522, whole Bible 1534), translated from the Hebrew and from Erasmus's Greek, in the churches' revision of 1912 — the last one out of copyright. It arrives tagged: about half its words carry a Strong number.",
                "Німецька Біблія Мартіна Лютера (Новий Заповіт — 1522, уся Біблія — 1534), перекладена з єврейської та з грецького тексту Еразма, у церковній редакції 1912 року — останній, на яку вже не поширюється авторське право. Вона має розмітку: близько половини слів мають номер Стронга.",
                "Martin Luthers deutsche Bibel (Neues Testament 1522, ganze Bibel 1534), aus dem Hebräischen und aus dem Griechisch des Erasmus übersetzt, in der kirchlichen Revision von 1912 – der letzten, die gemeinfrei ist. Sie ist annotiert: etwa die Hälfte ihrer Wörter trägt eine Strong-Nummer.",
                "La Biblia alemana de Martín Lutero (Nuevo Testamento 1522, Biblia completa 1534), traducida del hebreo y del griego de Erasmo, en la revisión eclesiástica de 1912, la última libre de derechos de autor. Viene etiquetada: cerca de la mitad de sus palabras llevan un número Strong."),
            ["ELB1905"] = Say(
                "The literal German Bible of the Brethren: John Nelson Darby, Carl Brockhaus and Julius Anton von Poseck published it at Elberfeld (New Testament 1855, whole Bible 1871), keeping the Hebrew and Greek word order wherever German allows. The unrevised edition of 1905.",
                "Дослівна німецька Біблія «братів»: Джон Нельсон Дарбі, Карл Брокгаус і Юліус Антон фон Позек видали її в Ельберфельді (Новий Заповіт — 1855, уся Біблія — 1871), зберігаючи порядок слів єврейського й грецького тексту скрізь, де це дозволяє німецька мова. Неперероблене видання 1905 року.",
                "Die wörtliche deutsche Bibel der Brüderbewegung: John Nelson Darby, Carl Brockhaus und Julius Anton von Poseck gaben sie in Elberfeld heraus (Neues Testament 1855, ganze Bibel 1871) und bewahrten die hebräische und griechische Wortstellung, wo das Deutsche es zulässt. Die unrevidierte Ausgabe von 1905.",
                "La Biblia alemana literal de los Hermanos: John Nelson Darby, Carl Brockhaus y Julius Anton von Poseck la publicaron en Elberfeld (Nuevo Testamento 1855, Biblia completa 1871), conservando el orden de palabras hebreo y griego siempre que el alemán lo permite. La edición sin revisar de 1905."),
            ["RV1909"] = Say(
                "Casiodoro de Reina's Spanish Bible, printed at Basel in 1569 and revised by Cipriano de Valera in 1602, in the revision of 1909 — the last Reina-Valera out of copyright. Its New Testament follows the Textus Receptus.",
                "Іспанська Біблія Касіодоро де Рейни, надрукована в Базелі 1569 року й переглянута Сиприано де Валерою 1602 року, у редакції 1909 року — останній Рейна-Валера, на яку не поширюється авторське право. Її Новий Заповіт іде за Textus Receptus.",
                "Casiodoro de Reinas spanische Bibel, 1569 in Basel gedruckt und 1602 von Cipriano de Valera überarbeitet, in der Revision von 1909 – der letzten gemeinfreien Reina-Valera. Ihr Neues Testament folgt dem Textus receptus.",
                "La Biblia española de Casiodoro de Reina, impresa en Basilea en 1569 y revisada por Cipriano de Valera en 1602, en la revisión de 1909, la última Reina-Valera libre de derechos de autor. Su Nuevo Testamento sigue el Texto Recibido."),
            ["CUV"] = Say(
                "The Chinese Union Version of 1919, the Bible most Chinese Protestants still read: one translation into the Mandarin people spoke, made by the missionary societies in China with their Chinese colleagues. In traditional characters, as the Faith Hope Love foundation typed it from the 1919 printing and punctuated it; its New Testament follows the Greek behind the English Revised Version.",
                "Китайський Союзний переклад 1919 року — Біблія, яку досі читає більшість китайських протестантів: єдиний переклад розмовною мандаринською, зроблений місіонерськими товариствами в Китаї разом із китайськими співробітниками. Традиційними ієрогліфами, як його набрав із друку 1919 року й розставив розділові знаки фонд «Віра, Надія, Любов»; Новий Заповіт іде за грецьким текстом англійської Revised Version.",
                "Die chinesische Union Version von 1919, die Bibel, die die meisten chinesischen Protestanten bis heute lesen: eine Übersetzung in das gesprochene Mandarin, von den Missionsgesellschaften in China mit ihren chinesischen Mitarbeitern geschaffen. In traditionellen Schriftzeichen, wie die Stiftung Faith Hope Love sie nach dem Druck von 1919 abgeschrieben und interpunktiert hat; ihr Neues Testament folgt dem griechischen Text der englischen Revised Version.",
                "La Versión de la Unión china de 1919, la Biblia que aún lee la mayoría de los protestantes chinos: una sola traducción al mandarín hablado, hecha por las sociedades misioneras en China con sus colaboradores chinos. En caracteres tradicionales, tal como la fundación Fe, Esperanza y Amor la transcribió de la impresión de 1919 y la puntuó; su Nuevo Testamento sigue el griego de la Revised Version inglesa."),
            ["CUVS"] = Say(
                "The Chinese Union Version of 1919 in simplified characters, the script most of its readers use: the same text as the traditional one, converted by the Faith Hope Love foundation.",
                "Китайський Союзний переклад 1919 року спрощеними ієрогліфами, якими користується більшість його читачів: той самий текст, що й традиційний, у перетворенні фонду «Віра, Надія, Любов».",
                "Die chinesische Union Version von 1919 in vereinfachten Schriftzeichen, der Schrift der meisten ihrer Leser: derselbe Text wie der traditionelle, von der Stiftung Faith Hope Love umgesetzt.",
                "La Versión de la Unión china de 1919 en caracteres simplificados, la escritura que usa la mayoría de sus lectores: el mismo texto que el tradicional, convertido por la fundación Fe, Esperanza y Amor."),
            ["KRV"] = Say(
                "The Korean Revised Version of 1961 (개역한글), the Korean Bible Society's revision of its 1938 translation and the Bible of Korean Protestants until 1998. Each word is printed as Korean writes it, with its particles attached; its New Testament follows the critical Greek text.",
                "Корейський виправлений переклад 1961 року (개역한글) — редакція перекладу 1938 року, здійснена Корейським біблійним товариством, Біблія корейських протестантів до 1998 року. Кожне слово подано так, як його пише корейська, разом із частками; Новий Заповіт іде за грецьким критичним текстом.",
                "Die koreanische revidierte Übersetzung von 1961 (개역한글), die Revision der Übersetzung von 1938 durch die Koreanische Bibelgesellschaft und bis 1998 die Bibel der koreanischen Protestanten. Jedes Wort steht so, wie das Koreanische es schreibt, mit angehängten Partikeln; ihr Neues Testament folgt dem kritischen griechischen Text.",
                "La Versión Revisada coreana de 1961 (개역한글), la revisión que la Sociedad Bíblica de Corea hizo de su traducción de 1938 y la Biblia de los protestantes coreanos hasta 1998. Cada palabra aparece como la escribe el coreano, con sus partículas unidas; su Nuevo Testamento sigue el texto crítico griego."),
            ["RUSV"] = Say(
                "The Russian Synodal translation, begun in 1813, resumed under Alexander II and completed in 1876, with the Old Testament translated from the Masoretic text. Words the Septuagint has and the Hebrew lacks are printed in square brackets.",
                "Російський синодальний переклад: розпочатий 1813 року, відновлений за Олександра II й завершений 1876 року; Старий Заповіт перекладено з масоретського тексту. Слова, які є в Септуагінті, але яких немає в єврейському тексті, надруковано у квадратних дужках.",
                "Die russische Synodalübersetzung, 1813 begonnen, unter Alexander II. wieder aufgenommen und 1876 vollendet; das Alte Testament ist aus dem masoretischen Text übersetzt. Wörter, die die Septuaginta hat und der hebräische Text nicht, stehen in eckigen Klammern.",
                "La traducción sinodal rusa, iniciada en 1813, retomada bajo Alejandro II y terminada en 1876, con el Antiguo Testamento traducido del texto masorético. Las palabras que tiene la Septuaginta y le faltan al hebreo se imprimen entre corchetes."),
            ["UBIO"] = Say(
                "Ivan Ohienko's Ukrainian translation from the Hebrew and Greek, begun in 1917, finished in 1940 and first printed complete in London in 1962. Whether the rights in the 1962 edition have been released is not settled.",
                "Український переклад Івана Огієнка з єврейської та грецької, розпочатий 1917 року, завершений 1940-го й уперше повністю надрукований у Лондоні 1962 року. Чи звільнено права на видання 1962 року, не з'ясовано.",
                "Iwan Ohijenkos ukrainische Übersetzung aus dem Hebräischen und Griechischen, 1917 begonnen, 1940 vollendet und 1962 in London erstmals vollständig gedruckt. Ob die Rechte an der Ausgabe von 1962 freigegeben sind, ist nicht geklärt.",
                "La traducción ucraniana de Iván Ohienko desde el hebreo y el griego, comenzada en 1917, terminada en 1940 e impresa completa por primera vez en Londres en 1962. No está aclarado si se han liberado los derechos de la edición de 1962."),
            ["UKR1871"] = Say(
                "The first complete Bible in modern literary Ukrainian. Panteleimon Kulish began it in the 1860s and with Ivan Puliui published the New Testament in Vienna in 1871; after his death Puliui and Ivan Nechui-Levytsky finished it, and the whole Bible was printed in 1903. Kulish's own spelling is kept.",
                "Перша повна Біблія сучасною українською літературною мовою. Пантелеймон Куліш почав її в 1860-х роках і разом з Іваном Пулюєм видав Новий Заповіт у Відні 1871 року; після його смерті переклад завершили Пулюй та Іван Нечуй-Левицький, і всю Біблію надруковано 1903 року. Правопис Куліша збережено.",
                "Die erste vollständige Bibel im modernen literarischen Ukrainisch. Pantelejmon Kulisch begann sie in den 1860er-Jahren und gab 1871 mit Iwan Puljuj in Wien das Neue Testament heraus; nach seinem Tod vollendeten Puljuj und Iwan Netschuj-Lewyzkyj sie, und die ganze Bibel erschien 1903. Kulischs eigene Schreibung ist beibehalten.",
                "La primera Biblia completa en ucraniano literario moderno. Panteleimón Kulish la empezó en la década de 1860 y con Iván Puliui publicó el Nuevo Testamento en Viena en 1871; tras su muerte, Puliui e Iván Nechui-Levytski la terminaron, y la Biblia completa se imprimió en 1903. Se conserva la ortografía del propio Kulish."),
            ["NPU2022"] = Say(
                "A new translation into present-day Ukrainian by Biblica, published in 2022 as the New Testament and the Psalms; the rest of the Old Testament has not appeared. Its New Testament follows the critical Greek text, and its Psalms are numbered as the Hebrew numbers them.",
                "Новий переклад сучасною українською мовою від Biblica, виданий 2022 року як Новий Заповіт і Псалми; решта Старого Заповіту не виходила. Новий Заповіт іде за грецьким критичним текстом, а Псалми пронумеровано так, як їх нумерує єврейський текст.",
                "Eine neue Übersetzung ins heutige Ukrainisch von Biblica, 2022 als Neues Testament und Psalmen erschienen; das übrige Alte Testament ist nicht veröffentlicht. Ihr Neues Testament folgt dem kritischen griechischen Text, ihre Psalmen sind gezählt, wie der hebräische Text sie zählt.",
                "Una nueva traducción al ucraniano actual de Biblica, publicada en 2022 como el Nuevo Testamento y los Salmos; el resto del Antiguo Testamento no ha aparecido. Su Nuevo Testamento sigue el texto crítico griego y sus Salmos se numeran como los numera el hebreo."),
            ["LSG1910"] = Say(
                "Louis Segond's French Bible, translated by a pastor of Geneva from the Hebrew (1874) and the Greek (1880), in the revision of 1910 — the Bible French Protestants read for most of the twentieth century, and the last Segond out of copyright.",
                "Французька Біблія Луї Сегона, женевського пастора, перекладена з єврейської (1874) і грецької (1880), у редакції 1910 року — Біблія, яку французькі протестанти читали більшу частину ХХ століття, і остання версія Сегона, вільна від авторських прав.",
                "Die französische Bibel Louis Segonds, eines Genfer Pfarrers, aus dem Hebräischen (1874) und dem Griechischen (1880) übersetzt, in der Revision von 1910 – die Bibel der französischen Protestanten für den größten Teil des 20. Jahrhunderts und der letzte gemeinfreie Segond.",
                "La Biblia francesa de Louis Segond, pastor de Ginebra, traducida del hebreo (1874) y del griego (1880), en la revisión de 1910: la Biblia que leyeron los protestantes franceses durante la mayor parte del siglo XX y el último Segond libre de derechos."),
            ["ALM1911"] = Say(
                "The first Bible in Portuguese. João Ferreira de Almeida translated the New Testament from the Received Text, printed in 1681, and died in 1691 in the middle of Ezekiel; others finished the Old Testament. This is the Revista e Corrigida of 1900 as reprinted in Lisbon in 1911, in the spelling of its day.",
                "Перша Біблія португальською мовою. Жуан Феррейра де Алмейда переклав Новий Заповіт із Textus Receptus (надруковано 1681 року) і помер 1691 року, дійшовши до середини Єзекіїля; Старий Заповіт завершили інші. Тут — редакція Revista e Corrigida 1900 року в лісабонському передруку 1911 року, з тогочасним правописом.",
                "Die erste Bibel auf Portugiesisch. João Ferreira de Almeida übersetzte das Neue Testament aus dem Textus receptus, gedruckt 1681, und starb 1691 mitten in Ezechiel; andere vollendeten das Alte Testament. Dies ist die Revista e Corrigida von 1900 im Lissabonner Nachdruck von 1911, in der Schreibung ihrer Zeit.",
                "La primera Biblia en portugués. João Ferreira de Almeida tradujo el Nuevo Testamento del Texto Recibido, impreso en 1681, y murió en 1691 a mitad de Ezequiel; otros terminaron el Antiguo Testamento. Esta es la Revista e Corrigida de 1900 en la reimpresión de Lisboa de 1911, con la ortografía de su tiempo."),
            ["AVD1865"] = Say(
                "The Arabic Bible of the American mission in Beirut, begun by Eli Smith in 1847 and finished by Cornelius Van Dyck in 1865 — the Bible of the Arabic-speaking Protestant churches, printed fully vowelled.",
                "Арабська Біблія американської місії в Бейруті, яку 1847 року почав Елі Сміт, а 1865 року завершив Корнеліус ван Дайк, — Біблія арабомовних протестантських церков, надрукована з повною огласовкою.",
                "Die arabische Bibel der amerikanischen Mission in Beirut, 1847 von Eli Smith begonnen und 1865 von Cornelius Van Dyck vollendet – die Bibel der arabischsprachigen protestantischen Kirchen, voll vokalisiert gedruckt.",
                "La Biblia árabe de la misión estadounidense en Beirut, comenzada por Eli Smith en 1847 y terminada por Cornelius Van Dyck en 1865: la Biblia de las iglesias protestantes de habla árabe, impresa totalmente vocalizada."),
            ["IRV2019"] = Say(
                "The Indian Revised Version in Hindi, a revision prepared between 2017 and 2019 and released under an open licence — the only complete Hindi Bible anyone may take. Its New Testament follows the critical Greek text.",
                "Індійська виправлена версія мовою гінді — редакція, підготовлена у 2017–2019 роках і випущена під відкритою ліцензією; це єдина повна Біблія гінді, яку може взяти будь-хто. Новий Заповіт іде за грецьким критичним текстом.",
                "Die Indian Revised Version auf Hindi, eine zwischen 2017 und 2019 erarbeitete Revision unter offener Lizenz – die einzige vollständige Hindi-Bibel, die jeder übernehmen darf. Ihr Neues Testament folgt dem kritischen griechischen Text.",
                "La Indian Revised Version en hindi, una revisión preparada entre 2017 y 2019 y publicada con licencia abierta: la única Biblia completa en hindi que cualquiera puede tomar. Su Nuevo Testamento sigue el texto crítico griego."),
            ["ULT"] = Say(
                "unfoldingWord's Literal Text, an open revision of the American Standard Version made to show the form of the Hebrew and Greek, keeping their word order wherever English will bear it. Every word is tied by hand to the original word it renders. Ten Old Testament books are still being checked and are not in this release.",
                "Буквальний текст unfoldingWord — відкрита редакція Американської стандартної версії, що показує будову єврейського й грецького тексту і зберігає їхній порядок слів, де це дозволяє англійська. Кожне слово вручну пов'язане зі словом оригіналу, яке воно передає. Десять книг Старого Заповіту ще перевіряють, і в цьому випуску їх немає.",
                "Der Literal Text von unfoldingWord, eine offene Revision der American Standard Version, die die Form des Hebräischen und Griechischen zeigen soll und deren Wortfolge beibehält, wo das Englische es zulässt. Jedes Wort ist von Hand mit dem Wort des Originals verbunden, das es wiedergibt. Zehn Bücher des Alten Testaments werden noch geprüft und fehlen in dieser Ausgabe.",
                "El Literal Text de unfoldingWord, una revisión abierta de la American Standard Version hecha para mostrar la forma del hebreo y del griego, que conserva su orden de palabras donde el inglés lo permite. Cada palabra está unida a mano a la palabra original que traduce. Diez libros del Antiguo Testamento aún se están revisando y no están en esta edición."),
        };

    /// <summary>The interface languages every summary is written in.</summary>
    public static readonly IReadOnlyList<string> Languages = ["en", "uk", "de", "es"];

    /// <summary>
    /// The summary of the text with this identifier, looked up under the identifier and under every
    /// spelling it answers to. Null for a text nobody has described yet.
    /// </summary>
    public static IReadOnlyDictionary<string, string>? For(string slug)
    {
        if (Written.TryGetValue(slug, out var summary))
        {
            return summary;
        }

        return TextAliases.Of(slug)
            .Select(alias => Written.GetValueOrDefault(alias))
            .FirstOrDefault(found => found is not null);
    }

    private static IReadOnlyDictionary<string, string> Say(string en, string uk, string de, string es) =>
        new Dictionary<string, string> { ["en"] = en, ["uk"] = uk, ["de"] = de, ["es"] = es };
}
