using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Essenthos.Core.Migrations
{
    /// <summary>
    /// Moves the source and note of every link and claim into <c>provenance</c>, and gives every link
    /// the fingerprint of its words with a unique constraint over it.
    ///
    /// <para>
    /// It runs on a corpus of tens of millions of links, so every step runs outside a transaction and
    /// is safe to run again: the rows are moved in batches of a million ids, each committed, and a
    /// batch already moved is passed over. A run that stops anywhere is finished by running it again.
    /// The last steps rewrite the two tables so the space the old columns held is given back; they
    /// take an exclusive lock, so nothing may be reading the corpus while it runs.
    /// </para>
    /// </summary>
    public partial class ASourceIsWrittenOnceAndTwoLinksCannotNameTheSameWords : Migration
    {
        private const string Shape =
            "md5(coalesce(string_agg(CASE WHEN lw.side = 'from' THEN 'f' ELSE 't' END || lw.word_id, ' ' " +
            "ORDER BY lw.side, lw.word_id), ''))::uuid";

        /// <summary>
        /// A link left with no words has no shape at all rather than the shape of nothing, so a step
        /// that takes a link's words out before the link itself is not refused for the moment between.
        /// </summary>
        private const string Emptied = $"CASE WHEN count(lw.word_id) = 0 THEN NULL ELSE {Shape} END";

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            Step(migrationBuilder,
                """
                CREATE TABLE IF NOT EXISTS provenance (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    source text NOT NULL,
                    note text,
                    CONSTRAINT pk_provenance PRIMARY KEY (id),
                    CONSTRAINT ck_provenance_source_not_empty CHECK (length(btrim("source")) > 0))
                """);
            Step(migrationBuilder,
                "CREATE UNIQUE INDEX IF NOT EXISTS ix_provenance_source_note ON provenance (source, note) NULLS NOT DISTINCT");
            Step(migrationBuilder,
                "ALTER TABLE link ADD COLUMN IF NOT EXISTS provenance_id integer, ADD COLUMN IF NOT EXISTS fingerprint uuid");
            Step(migrationBuilder, "ALTER TABLE link_claim ADD COLUMN IF NOT EXISTS provenance_id integer");

            // The source index is four gigabytes because it carries the text, and the one on the link
            // alone is the leading column of the index that replaces it; the index on a link's pair of
            // texts is the leading columns of the fingerprint's constraint. All three go before the
            // rows are rewritten, so the rewrite does not maintain them.
            Step(migrationBuilder, "DROP INDEX IF EXISTS ix_link_claim_link_id_method_source");
            Step(migrationBuilder, "DROP INDEX IF EXISTS ix_link_claim_link_id");
            Step(migrationBuilder, "DROP INDEX IF EXISTS ix_link_from_text_id_to_text_id");

            Step(migrationBuilder,
                $"""
                DO $$
                BEGIN
                    IF {StillHas("link", "source")} THEN
                        INSERT INTO provenance (source, note) SELECT DISTINCT source, note FROM link
                        ON CONFLICT (source, note) DO NOTHING;
                    END IF;
                    IF {StillHas("link_claim", "source")} THEN
                        INSERT INTO provenance (source, note) SELECT DISTINCT source, note FROM link_claim
                        ON CONFLICT (source, note) DO NOTHING;
                    END IF;
                END $$
                """);

            // Measured before the batches are planned: without it the planner takes the new column for
            // nearly empty and the new table for nothing, and reads provenance once for every link.
            Step(migrationBuilder, "ANALYZE provenance");
            Step(migrationBuilder, "ANALYZE link");
            Step(migrationBuilder, "ANALYZE link_claim");

            // A note and an absent note are matched apart, so each half is an equality the index on
            // (source, note) answers; IS NOT DISTINCT FROM is one no index can.
            Step(migrationBuilder,
                $"""
                DO $$
                DECLARE
                    first_id bigint;
                    last_id bigint;
                    batch constant bigint := 1000000;
                BEGIN
                    IF NOT {StillHas("link", "source")} THEN
                        RETURN;
                    END IF;
                    SELECT min(id), max(id) INTO first_id, last_id FROM link WHERE provenance_id IS NULL;
                    WHILE first_id <= last_id LOOP
                        UPDATE link l
                        SET provenance_id = said.provenance_id, fingerprint = shaped.fingerprint
                        FROM (
                            SELECT m.id, p.id AS provenance_id
                            FROM link m JOIN provenance p ON p.source = m.source AND p.note = m.note
                            WHERE m.id >= first_id AND m.id < first_id + batch AND m.provenance_id IS NULL
                            UNION ALL
                            SELECT m.id, p.id
                            FROM link m JOIN provenance p ON p.source = m.source AND p.note IS NULL
                            WHERE m.id >= first_id AND m.id < first_id + batch AND m.provenance_id IS NULL
                              AND m.note IS NULL) said
                        LEFT JOIN (
                            SELECT lw.link_id, {Shape} AS fingerprint
                            FROM link_word lw
                            WHERE lw.link_id >= first_id AND lw.link_id < first_id + batch
                            GROUP BY lw.link_id) shaped ON shaped.link_id = said.id
                        WHERE l.id = said.id;
                        COMMIT;
                        first_id := first_id + batch;
                    END LOOP;
                END $$
                """);

            Step(migrationBuilder,
                $"""
                DO $$
                DECLARE
                    first_id bigint;
                    last_id bigint;
                    batch constant bigint := 1000000;
                BEGIN
                    IF NOT {StillHas("link_claim", "source")} THEN
                        RETURN;
                    END IF;
                    SELECT min(id), max(id) INTO first_id, last_id FROM link_claim WHERE provenance_id IS NULL;
                    WHILE first_id <= last_id LOOP
                        UPDATE link_claim c
                        SET provenance_id = said.provenance_id
                        FROM (
                            SELECT m.id, p.id AS provenance_id
                            FROM link_claim m JOIN provenance p ON p.source = m.source AND p.note = m.note
                            WHERE m.id >= first_id AND m.id < first_id + batch AND m.provenance_id IS NULL
                            UNION ALL
                            SELECT m.id, p.id
                            FROM link_claim m JOIN provenance p ON p.source = m.source AND p.note IS NULL
                            WHERE m.id >= first_id AND m.id < first_id + batch AND m.provenance_id IS NULL
                              AND m.note IS NULL) said
                        WHERE c.id = said.id;
                        COMMIT;
                        first_id := first_id + batch;
                    END LOOP;
                END $$
                """);

            Step(migrationBuilder, "ALTER TABLE link ALTER COLUMN provenance_id SET NOT NULL");
            Step(migrationBuilder, "ALTER TABLE link_claim ALTER COLUMN provenance_id SET NOT NULL");
            Step(migrationBuilder, ForeignKey("link", "fk_link_provenances_provenance_id"));
            Step(migrationBuilder, ForeignKey("link_claim", "fk_link_claim_provenances_provenance_id"));

            Step(migrationBuilder,
                "ALTER TABLE link DROP CONSTRAINT IF EXISTS ck_link_source_not_empty, " +
                "DROP COLUMN IF EXISTS source, DROP COLUMN IF EXISTS note");
            Step(migrationBuilder,
                "ALTER TABLE link_claim DROP CONSTRAINT IF EXISTS ck_link_claim_source_not_empty, " +
                "DROP COLUMN IF EXISTS source, DROP COLUMN IF EXISTS note");

            Step(migrationBuilder,
                "CREATE UNIQUE INDEX IF NOT EXISTS ix_link_claim_link_id_method_provenance_id " +
                "ON link_claim (link_id, method, provenance_id)");

            // Deferred to commit: a link is written in one statement and its words in the next, and a
            // shape is only whole once both are in.
            Step(migrationBuilder,
                """
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                                   WHERE conname = 'ix_link_from_text_id_to_text_id_fingerprint') THEN
                        ALTER TABLE link ADD CONSTRAINT ix_link_from_text_id_to_text_id_fingerprint
                            UNIQUE (from_text_id, to_text_id, fingerprint) DEFERRABLE INITIALLY DEFERRED;
                    END IF;
                END $$
                """);
            // Whoever changes a link's words, the fingerprint follows, once per statement over every
            // link the statement touched; a writer that already wrote the right value costs a read and
            // no write. A link deleted with its words is gone before this runs and is not looked for.
            Step(migrationBuilder,
                $"""
                CREATE OR REPLACE FUNCTION link_shape_follows_its_words() RETURNS trigger
                LANGUAGE plpgsql AS $$
                BEGIN
                    IF TG_OP = 'INSERT' THEN
                        UPDATE link l SET fingerprint = shaped.fingerprint
                        FROM (SELECT lw.link_id, {Shape} AS fingerprint
                              FROM link_word lw
                              WHERE lw.link_id IN (SELECT link_id FROM added)
                              GROUP BY lw.link_id) shaped
                        WHERE l.id = shaped.link_id AND l.fingerprint IS DISTINCT FROM shaped.fingerprint;
                    ELSIF TG_OP = 'DELETE' THEN
                        UPDATE link l SET fingerprint = shaped.fingerprint
                        FROM (SELECT t.id AS link_id, {Emptied} AS fingerprint
                              FROM link t
                              LEFT JOIN link_word lw ON lw.link_id = t.id
                              WHERE t.id IN (SELECT link_id FROM removed)
                              GROUP BY t.id) shaped
                        WHERE l.id = shaped.link_id AND l.fingerprint IS DISTINCT FROM shaped.fingerprint;
                    ELSE
                        UPDATE link l SET fingerprint = shaped.fingerprint
                        FROM (SELECT t.id AS link_id, {Emptied} AS fingerprint
                              FROM link t
                              LEFT JOIN link_word lw ON lw.link_id = t.id
                              WHERE t.id IN (SELECT link_id FROM removed UNION SELECT link_id FROM added)
                              GROUP BY t.id) shaped
                        WHERE l.id = shaped.link_id AND l.fingerprint IS DISTINCT FROM shaped.fingerprint;
                    END IF;
                    RETURN NULL;
                END $$
                """);
            Step(migrationBuilder,
                "CREATE OR REPLACE TRIGGER link_word_added AFTER INSERT ON link_word " +
                "REFERENCING NEW TABLE AS added FOR EACH STATEMENT EXECUTE FUNCTION link_shape_follows_its_words()");
            Step(migrationBuilder,
                "CREATE OR REPLACE TRIGGER link_word_removed AFTER DELETE ON link_word " +
                "REFERENCING OLD TABLE AS removed FOR EACH STATEMENT EXECUTE FUNCTION link_shape_follows_its_words()");
            Step(migrationBuilder,
                "CREATE OR REPLACE TRIGGER link_word_changed AFTER UPDATE ON link_word " +
                "REFERENCING OLD TABLE AS removed NEW TABLE AS added " +
                "FOR EACH STATEMENT EXECUTE FUNCTION link_shape_follows_its_words()");

            // Rewritten, so the rows give back what their old columns and the batches' old versions
            // held, and measured, so the planner knows the tables it is now reading.
            Step(migrationBuilder, "VACUUM (FULL, ANALYZE) link");
            Step(migrationBuilder, "VACUUM (FULL, ANALYZE) link_claim");
            Step(migrationBuilder, "VACUUM (ANALYZE) provenance");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            Step(migrationBuilder, "DROP TRIGGER IF EXISTS link_word_added ON link_word");
            Step(migrationBuilder, "DROP TRIGGER IF EXISTS link_word_removed ON link_word");
            Step(migrationBuilder, "DROP TRIGGER IF EXISTS link_word_changed ON link_word");
            Step(migrationBuilder, "DROP FUNCTION IF EXISTS link_shape_follows_its_words()");
            Step(migrationBuilder,
                "CREATE INDEX IF NOT EXISTS ix_link_from_text_id_to_text_id ON link (from_text_id, to_text_id)");
            Step(migrationBuilder,
                "ALTER TABLE link DROP CONSTRAINT IF EXISTS ix_link_from_text_id_to_text_id_fingerprint");

            Step(migrationBuilder,
                "ALTER TABLE link ADD COLUMN IF NOT EXISTS source text, ADD COLUMN IF NOT EXISTS note text");
            Step(migrationBuilder,
                "ALTER TABLE link_claim ADD COLUMN IF NOT EXISTS source text, ADD COLUMN IF NOT EXISTS note text");
            Step(migrationBuilder,
                $"""
                DO $$
                BEGIN
                    IF {StillHas("link", "provenance_id")} THEN
                        UPDATE link l SET source = p.source, note = p.note
                        FROM provenance p WHERE p.id = l.provenance_id AND l.source IS NULL;
                    END IF;
                    IF {StillHas("link_claim", "provenance_id")} THEN
                        UPDATE link_claim c SET source = p.source, note = p.note
                        FROM provenance p WHERE p.id = c.provenance_id AND c.source IS NULL;
                    END IF;
                END $$
                """);
            Step(migrationBuilder, "ALTER TABLE link ALTER COLUMN source SET NOT NULL");
            Step(migrationBuilder, "ALTER TABLE link_claim ALTER COLUMN source SET NOT NULL");
            Step(migrationBuilder,
                "ALTER TABLE link DROP COLUMN IF EXISTS provenance_id, DROP COLUMN IF EXISTS fingerprint");
            Step(migrationBuilder,
                "ALTER TABLE link_claim DROP COLUMN IF EXISTS provenance_id");
            Step(migrationBuilder, "DROP TABLE IF EXISTS provenance");

            Step(migrationBuilder,
                """
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_link_source_not_empty') THEN
                        ALTER TABLE link ADD CONSTRAINT ck_link_source_not_empty CHECK (length(btrim("source")) > 0);
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_link_claim_source_not_empty') THEN
                        ALTER TABLE link_claim ADD CONSTRAINT ck_link_claim_source_not_empty
                            CHECK (length(btrim("source")) > 0);
                    END IF;
                END $$
                """);
            Step(migrationBuilder,
                "DROP INDEX IF EXISTS ix_link_claim_link_id_method_provenance_id");
            Step(migrationBuilder,
                "CREATE INDEX IF NOT EXISTS ix_link_claim_link_id ON link_claim (link_id)");
            Step(migrationBuilder,
                "CREATE UNIQUE INDEX IF NOT EXISTS ix_link_claim_link_id_method_source " +
                "ON link_claim (link_id, method, source)");
        }

        private static void Step(MigrationBuilder migrationBuilder, string sql) =>
            migrationBuilder.Sql(sql, suppressTransaction: true);

        private static string StillHas(string table, string column) =>
            "EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() " +
            $"AND table_name = '{table}' AND column_name = '{column}')";

        private static string ForeignKey(string table, string name) =>
            $"""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = '{name}') THEN
                    ALTER TABLE {table} ADD CONSTRAINT {name}
                        FOREIGN KEY (provenance_id) REFERENCES provenance (id) ON DELETE RESTRICT;
                END IF;
            END $$
            """;
    }
}
