<#
.SYNOPSIS
    Fetches MACULA Greek's word-level annotation of Nestle 1904 — the first source in this corpus
    that states, rather than lets us infer, which Greek words are proper nouns.

.DESCRIPTION
    Nestle's own morphology says `noun` 28,394 times and never *proper noun*, so the Greek naming
    pass had to build a gate out of the lexicon's capital letter and measure it three ways against
    independent sources. MACULA writes `type="proper"` on the word itself, and it writes it on the
    Nestle 1904 words: the same edition this corpus already holds, from the same upstream
    repository, with `ref="MAT 1:1!1"` on every one of them.

    That is why this is a fetch and not an alignment. MorphGNT parses a different edition and had
    to be joined to ours word by word; this is the same 137,779 words in the same 7,943 verses, and
    the loader refuses to write anything at all unless every verse still has the same number of
    words on both sides. A dataset that claims to be about our text has to prove it before its
    claims are stored as though our text made them.

    Only the word table is taken. `Nestle1904/tsv/macula-greek-Nestle1904.tsv` is a flat row per
    word, 19 MB, generated by the repository's own query from the syntax trees beside it; the trees
    themselves are 110 MB of `lowfat` XML and carry the clause structure, which is a different piece
    of work with a different shape in the schema and is deliberately left where it is.

    The licence is read here rather than trusted. It is CC BY 4.0 — no ShareAlike, no
    NonCommercial — stated in `LICENSE.md` with the attribution string given verbatim, and GitHub's
    own badge says `NOASSERTION` because the file is named `LICENSE.md` rather than `LICENSE`. The
    badge is wrong and the file is the statement. If either the licence sentence or the attribution
    string stops saying what it says today, this stops and replaces nothing.

.EXAMPLE
    ./scripts/fetch-macula.ps1
#>

[CmdletBinding()]
param(
    # The default matches Dataset:ResourcesPath: this project's own Resources folder.
    [string] $ResourcesPath = (Join-Path $PSScriptRoot '..' 'Resources'),

    # A branch, tag or commit of Clear-Bible/macula-greek. Pinned in Resources/Macula/LICENCE.md;
    # main is the default because the repository publishes no release tags.
    [string] $Ref = 'main'
)

$ErrorActionPreference = 'Stop'

$Repository = 'Clear-Bible/macula-greek'

# The three sentences that carry the terms. The first is the grant, the second is the condition,
# and the third is the one that says the words underneath are not Clear's own — the Nestle 1904
# transcription and morphology are biblicalhumanities.org's and are CC0, which is what
# Resources/Nestle1904/LICENCE.md already records.
$ExpectedLicence = 'is licensed under [CC BY 4.0 ](http://creativecommons.org/licenses/by/4.0/)'
$ExpectedAttribution = 'MACULA Greek Linguistic Datasets, available at https://github.com/Clear-Bible/macula-greek/'
$ExpectedBase = '[Nestle1904](https://github.com/biblicalhumanities/Nestle1904) Greek New Testament'

$Table = 'Nestle1904/tsv/macula-greek-Nestle1904.tsv'

# One row per word of Nestle 1904, and it must be exactly the number of words this corpus holds:
# the whole point of this source is that it needs no alignment, and a short download would look
# like a shorter edition rather than like a failure.
$ExpectedWords = 137779

# The columns the loader reads by name, in the header the query writes. A header that has lost one
# of them is a format change and not a download to keep.
$Columns = @(
    'xml:id', 'ref', 'class', 'type', 'lemma', 'normalized', 'strong', 'morph',
    'person', 'number', 'gender', 'case', 'tense', 'voice', 'mood', 'degree', 'text'
)

$commit = (Invoke-RestMethod -Uri "https://api.github.com/repos/$Repository/commits/$Ref" `
    -Headers @{ 'User-Agent' = 'essenthos' }).sha
$raw = "https://raw.githubusercontent.com/$Repository/$commit"

$staging = Join-Path ([IO.Path]::GetTempPath()) "macula-$([guid]::NewGuid().ToString('n'))"
New-Item -ItemType Directory -Force -Path (Join-Path $staging 'tsv') | Out-Null

try {
    Write-Host "Fetching $Repository at $($commit.Substring(0, 7))"

    Invoke-WebRequest -Uri "$raw/LICENSE.md" -OutFile (Join-Path $staging 'LICENSE-upstream.md')
    Invoke-WebRequest -Uri "$raw/README.md" -OutFile (Join-Path $staging 'README-upstream.md')
    $licence = Get-Content (Join-Path $staging 'LICENSE-upstream.md') -Raw

    if ($licence -notmatch [regex]::Escape($ExpectedLicence)) {
        throw "LICENSE.md no longer licenses the MACULA Greek datasets under CC BY 4.0. That " +
              "sentence is why this data can be taken without weighing a ShareAlike or a " +
              "NonCommercial clause, so a change to it is the owner's decision and not a " +
              "download: nothing was replaced. Read the new statement before fetching again."
    }

    if ($licence -notmatch [regex]::Escape($ExpectedAttribution)) {
        throw "LICENSE.md no longer gives the attribution string this corpus records on every " +
              "row it loads from here. CC BY is a licence whose one condition is that wording, so " +
              "a change to it has to be carried into Resources/Macula/LICENCE.md and into the " +
              "loader's source line by a person; nothing was replaced."
    }

    if ($licence -notmatch [regex]::Escape($ExpectedBase)) {
        throw "LICENSE.md no longer names biblicalhumanities.org's Nestle 1904 as the text these " +
              "annotations stand on. This corpus holds that same edition and joins to it by " +
              "address alone; a MACULA built over some other Greek text would need an alignment " +
              "that does not exist here. Nothing was replaced."
    }

    $file = Join-Path $staging 'tsv\macula-greek-Nestle1904.tsv'
    Invoke-WebRequest -Uri "$raw/$Table" -OutFile $file

    $lines = [IO.File]::ReadAllLines($file)
    $header = $lines[0] -split "`t"
    foreach ($column in $Columns) {
        if ($header -notcontains $column) {
            throw "The word table has no column named '$column'. The query that generates it is " +
                  "mappings/greek-lowfat-to-tsv.xq and its output has changed; the reader has to " +
                  "change with it before anything is loaded. Nothing was replaced."
        }
    }

    $words = $lines.Length - 1
    if ($words -ne $ExpectedWords) {
        throw "The word table holds $words words and Nestle 1904 has $ExpectedWords. This source " +
              "is taken because it needs no alignment, and that rests on the two being the same " +
              "words in the same order; nothing was replaced. If the edition genuinely changed, " +
              "the correspondence has to be re-measured before the count here is moved."
    }

    $root = Join-Path (Resolve-Path $ResourcesPath) 'Macula'
    New-Item -ItemType Directory -Force -Path $root | Out-Null
    Copy-Item -Path (Join-Path $staging '*') -Destination $root -Recurse -Force

    $size = (Get-ChildItem $root -Recurse -File | Measure-Object -Property Length -Sum).Sum / 1MB
    Write-Host ("{0:N0} annotated words of Nestle 1904, {1:N1} MB in {2}" -f $words, $size, $root)
    Write-Host "Taken from github.com/$Repository at $commit"
    Write-Host "Record that commit in $root\LICENCE.md if this replaced an earlier fetch."
    Write-Host "Then run: python scripts/corpus-manifest.py, and commit the manifest."
    Write-Host ("A reload is not automatic: the loader returns early once any Nestle word carries " +
                "a MACULA annotation, so a restart alone picks nothing up.")
}
finally {
    Remove-Item -Recurse -Force $staging -ErrorAction SilentlyContinue
}
