<#
.SYNOPSIS
    Fetches the pictures of people and places: OpenBible.info's place thumbnails, with the metadata
    that credits and licenses each one, and the curated public works Essenthos.Forge lists.

.DESCRIPTION
    Places: the gazetteer's image.jsonl, taken from the same commit as the ancient.jsonl beside it,
    because it is where each thumbnail's licence is stated — the dataset's own CC BY 4.0 does not
    reach its photographs. Then the 512x512 thumbnail archive (about 180 MB), unpacked into
    Resources/Images/openbible. The archive is kept in Resources/OpenBible so a second run unpacks
    without downloading.

    People: every entry of Essenthos.Forge/Loading/Encyclopedia/PublicImages.json that has a
    download address is fetched into the path under Resources/Images its entry names, unless the
    file is already there.

    Generated portraits are not fetched by anything: they are ours, and go into
    Resources/Images/generated by hand beside a manifest.json.

    Nothing is loaded. After this, `dotnet run --project Essenthos.Forge -c Release -- images`
    writes the rows for an already loaded corpus; a full load does the same as its last step.

.EXAMPLE
    ./scripts/fetch-images.ps1
#>

[CmdletBinding()]
param(
    # The default matches Dataset:ResourcesPath: this project's own Resources folder.
    [string] $ResourcesPath = (Join-Path $PSScriptRoot '..' 'Resources'),

    # The Bible-Geocoding-Data commit ancient.jsonl was taken from, recorded in
    # Resources/OpenBible/LICENCE.md. The image metadata has to describe the same thumbnails.
    [string] $Ref = '7eb18a5ee62f27b9b93bd6689ea272d76dd23b8f',

    # Unpack the archive again even where the folder already holds it.
    [switch] $Force
)

$ErrorActionPreference = 'Stop'

$Repository = 'openbibleinfo/Bible-Geocoding-Data'
$Archive = 'https://a.openbible.info/geo/thumbnails.zip'
$UserAgent = 'essenthos/1.0 (pictures for a Bible encyclopedia)'

# The archive's own measure is 1,650 thumbnails; fewer means a partial download.
$FewestThumbnails = 1500

# Between two Commons downloads, and how many times one refused as too many requests is tried.
$PoliteSeconds = 2
$Attempts = 5

$resources = Resolve-Path $ResourcesPath
$gazetteer = Join-Path $resources 'OpenBible'
$images = Join-Path $resources 'Images'
$unpacked = Join-Path $images 'openbible'
New-Item -ItemType Directory -Force -Path $gazetteer, $images | Out-Null

Write-Host "Fetching image.jsonl from $Repository at $($Ref.Substring(0, 7))"
Invoke-WebRequest -Uri "https://raw.githubusercontent.com/$Repository/$Ref/data/image.jsonl" `
    -OutFile (Join-Path $gazetteer 'image.jsonl')

$zip = Join-Path $gazetteer 'thumbnails.zip'
if (-not (Test-Path $zip)) {
    Write-Host "Fetching $Archive (about 180 MB)"
    Invoke-WebRequest -Uri $Archive -OutFile "$zip.part" -Headers @{ 'User-Agent' = $UserAgent }
    Move-Item "$zip.part" $zip
}

if ($Force -or -not (Test-Path $unpacked) -or @(Get-ChildItem $unpacked -File).Count -lt $FewestThumbnails) {
    Write-Host "Unpacking the thumbnails into $unpacked"
    Expand-Archive -Path $zip -DestinationPath $unpacked -Force
}

$count = @(Get-ChildItem $unpacked -File -Recurse).Count
if ($count -lt $FewestThumbnails) {
    throw "$unpacked holds $count thumbnails and the archive measured 1,650. Delete $zip and run " +
          "this again: it is a partial download."
}
Write-Host ("{0:N0} place thumbnails in {1}" -f $count, $unpacked)

$manifest = Join-Path $PSScriptRoot '..' 'Essenthos.Forge' 'Loading' 'Encyclopedia' 'PublicImages.json'
$curated = Get-Content $manifest -Raw | ConvertFrom-Json
$fetched = 0
foreach ($entry in $curated.images) {
    if (-not $entry.download) {
        continue
    }

    $target = Join-Path $images ($entry.file -replace '/', [IO.Path]::DirectorySeparatorChar)
    if (Test-Path $target) {
        continue
    }

    New-Item -ItemType Directory -Force -Path (Split-Path $target) | Out-Null

    # Wikimedia asks automated clients to go slowly, and answers 429 to one that does not; each
    # refusal doubles the wait before the next try.
    $wait = $PoliteSeconds
    for ($attempt = 1; ; $attempt++) {
        Start-Sleep -Seconds $wait
        try {
            Invoke-WebRequest -Uri $entry.download -OutFile "$target.part" -Headers @{ 'User-Agent' = $UserAgent }
            Move-Item "$target.part" $target
            break
        }
        catch {
            if ($attempt -ge $Attempts -or $_.Exception.Response.StatusCode.value__ -ne 429) {
                throw "Could not fetch $($entry.download) for $($entry.entity): $($_.Exception.Message)"
            }
            $wait *= 2
        }
    }
    $fetched++
}
Write-Host "$fetched curated pictures fetched; $(@($curated.images).Count) listed"
Write-Host "Now: dotnet run --project Essenthos.Forge -c Release -- images"
