namespace Essenthos.Core.Macula;

/// <summary>
/// MACULA Greek's word table: one tab-separated row per word of Nestle 1904, with a header naming
/// its twenty-seven columns.
///
/// <code>
/// xml:id        ref         role  class  type    …  lemma   normalized  strong  morph  …
/// n40001001001  MAT 1:1!1         noun   common  …  βίβλος  Βίβλος      976     N-NSF  …
/// </code>
///
/// <para>
/// **Columns are read by name and never by position.** The file is generated by a query in the
/// repository — <c>mappings/greek-lowfat-to-tsv.xq</c> — over syntax trees that gain attributes as
/// the project adds datasets, so its column order is not a format anybody promised. A reader that
/// counted to seventeen would silently take the semantic domain for the mood the first time a
/// column was inserted; this one stops instead, and the fetch script checks the same header before
/// it replaces the file at all.
/// </para>
///
/// <para>
/// The address is <c>BOOK C:V!P</c> — a USFM book code, chapter, verse, and the word's index within
/// the verse from 1. That last number is what makes this dataset different from every other
/// annotation this corpus has taken: it is published over the same edition, so the position is the
/// join and there is nothing to infer.
/// </para>
/// </summary>
internal static class MaculaReader
{
    public const string File = "macula-greek-Nestle1904.tsv";

    /// <summary>
    /// The 27 books as MACULA addresses them, in canonical order, so a code's place in this list is
    /// its ordinal. USFM's codes, kept here rather than folded into the shared abbreviation table
    /// for the reason <c>KulishTextSource</c> gives: that table matches alternatives by scanning
    /// and the first match wins, so a second naming scheme in it changes what an existing alias
    /// resolves to.
    /// </summary>
    private static readonly string[] Canon =
    [
        "MAT", "MRK", "LUK", "JHN", "ACT", "ROM", "1CO", "2CO", "GAL", "EPH", "PHP", "COL", "1TH",
        "2TH", "1TI", "2TI", "TIT", "PHM", "HEB", "JAS", "1PE", "2PE", "1JN", "2JN", "3JN", "JUD",
        "REV",
    ];

    /// <summary>Matthew is the fortieth book of the canon and the first of these.</summary>
    private const int FirstNewTestamentBook = 40;

    private const char Separator = '\t';

    public static string Path(string folder) => System.IO.Path.Combine(folder, "tsv", File);

    /// <summary>Every annotated word, in the order the file writes them, which is document order.</summary>
    public static IReadOnlyList<MaculaWord> Read(string content)
    {
        var lines = content.Split('\n');
        if (lines.Length < 2)
        {
            throw new InvalidDataException(
                $"{File} has no rows under its header. Re-run scripts/fetch-macula.ps1.");
        }

        var columns = Columns(lines[0]);
        var words = new List<MaculaWord>(140_000);

        for (var at = 1; at < lines.Length; at++)
        {
            var line = lines[at].TrimEnd('\r');
            if (line.Length == 0)
            {
                continue;
            }

            var fields = line.Split(Separator);
            var (book, chapter, verse, position) = Address(Field(fields, columns, "ref"), at + 1);

            words.Add(new MaculaWord(
                Book: book,
                Chapter: chapter,
                Verse: verse,
                Position: position,
                Class: Value(fields, columns, "class"),
                Type: Value(fields, columns, "type"),
                Lemma: Value(fields, columns, "lemma"),
                Morph: Value(fields, columns, "morph"),
                Person: Value(fields, columns, "person"),
                Number: Value(fields, columns, "number"),
                Gender: Value(fields, columns, "gender"),
                Case: Value(fields, columns, "case"),
                Tense: Value(fields, columns, "tense"),
                Voice: Value(fields, columns, "voice"),
                Mood: Value(fields, columns, "mood"),
                Degree: Value(fields, columns, "degree"),
                Surface: Field(fields, columns, "text")));
        }

        return words;
    }

    public static IReadOnlyList<MaculaWord> ReadFile(string folder) =>
        Read(System.IO.File.ReadAllText(Path(folder)));

    /// <summary>Where each column the loader reads stands in this particular generation of the file.</summary>
    private static Dictionary<string, int> Columns(string header)
    {
        var names = header.TrimEnd('\r').Split(Separator);
        var columns = new Dictionary<string, int>(names.Length, StringComparer.Ordinal);

        for (var at = 0; at < names.Length; at++)
        {
            columns[names[at]] = at;
        }

        foreach (var required in (string[])["ref", "class", "type", "lemma", "morph", "case", "text"])
        {
            if (!columns.ContainsKey(required))
            {
                throw new InvalidDataException(
                    $"{File} has no column named \"{required}\", so this is not the table this " +
                    "reader was written for. The query that generates it is " +
                    "mappings/greek-lowfat-to-tsv.xq upstream; read the new header and change the " +
                    "reader before anything is loaded.");
            }
        }

        return columns;
    }

    /// <summary><c>MAT 1:1!1</c> — book, chapter, verse, and the word's index within the verse.</summary>
    private static (int Book, int Chapter, int Verse, int Position) Address(string reference, int line)
    {
        var space = reference.IndexOf(' ');
        var colon = reference.IndexOf(':');
        var bang = reference.IndexOf('!');

        if (space < 0 || colon < space || bang < colon)
        {
            throw new InvalidDataException(
                $"Line {line} of {File} addresses its word as \"{reference}\", which is not the " +
                "\"MAT 1:1!1\" this format uses. Re-run scripts/fetch-macula.ps1.");
        }

        var code = reference[..space];
        var book = Array.IndexOf(Canon, code);
        if (book < 0)
        {
            throw new InvalidDataException(
                $"Line {line} of {File} names a book \"{code}\", which is not one of the 27 this " +
                "dataset covers. MACULA Greek is the New Testament; a row outside it means the " +
                "file is not the one this reader was written for.");
        }

        return (
            book + FirstNewTestamentBook,
            int.Parse(reference[(space + 1)..colon]),
            int.Parse(reference[(colon + 1)..bang]),
            int.Parse(reference[(bang + 1)..]));
    }

    private static string Field(string[] fields, Dictionary<string, int> columns, string name)
    {
        var at = columns[name];
        return at < fields.Length ? fields[at] : string.Empty;
    }

    /// <summary>The same, with an empty cell read as absent — the file writes both the same way.</summary>
    private static string? Value(string[] fields, Dictionary<string, int> columns, string name)
    {
        if (!columns.TryGetValue(name, out var at) || at >= fields.Length)
        {
            return null;
        }

        var value = fields[at].Trim();
        return value.Length == 0 ? null : value;
    }
}
