// <auto-generated />
using System;
using System.Text.Json;
using Essenthos.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Essenthos.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902091723_VerseLabel")]
    partial class VerseLabel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Essenthos.Core.Database.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("text")
                        .HasColumnName("abbreviation");

                    b.Property<int>("CanonicalOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("canonical_ordinal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameNative")
                        .HasColumnType("text")
                        .HasColumnName("name_native");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("TextId")
                        .HasColumnType("integer")
                        .HasColumnName("text_id");

                    b.HasKey("Id")
                        .HasName("pk_book");

                    b.HasIndex("TextId", "CanonicalOrdinal")
                        .IsUnique()
                        .HasDatabaseName("ix_book_text_id_canonical_ordinal");

                    b.HasIndex("TextId", "Position")
                        .HasDatabaseName("ix_book_text_id_position");

                    b.HasIndex("TextId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_book_text_id_slug");

                    b.ToTable("book", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("TextId")
                        .HasColumnType("integer")
                        .HasColumnName("text_id");

                    b.HasKey("Id")
                        .HasName("pk_chapter");

                    b.HasIndex("TextId")
                        .HasDatabaseName("ix_chapter_text_id");

                    b.HasIndex("BookId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_chapter_book_id_number");

                    b.ToTable("chapter", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.Link", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<int>("FromTextId")
                        .HasColumnType("integer")
                        .HasColumnName("from_text_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relation");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<int>("ToTextId")
                        .HasColumnType("integer")
                        .HasColumnName("to_text_id");

                    b.HasKey("Id")
                        .HasName("pk_link");

                    b.HasIndex("ToTextId")
                        .HasDatabaseName("ix_link_to_text_id");

                    b.HasIndex("FromTextId", "ToTextId")
                        .HasDatabaseName("ix_link_from_text_id_to_text_id");

                    b.ToTable("link", null, t =>
                        {
                            t.HasCheckConstraint("ck_link_confidence_range", "\"confidence\" IS NULL OR (\"confidence\" >= 0 AND \"confidence\" <= 1)");

                            t.HasCheckConstraint("ck_link_inferred_carries_confidence", "\"method\" IN ('stated-by-source', 'manual') OR \"confidence\" IS NOT NULL");

                            t.HasCheckConstraint("ck_link_source_not_empty", "length(btrim(\"source\")) > 0");

                            t.HasCheckConstraint("ck_link_stated_carries_no_confidence", "\"method\" <> 'stated-by-source' OR \"confidence\" IS NULL");
                        });
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.LinkWord", b =>
                {
                    b.Property<long>("LinkId")
                        .HasColumnType("bigint")
                        .HasColumnName("link_id");

                    b.Property<long>("WordId")
                        .HasColumnType("bigint")
                        .HasColumnName("word_id");

                    b.Property<string>("Side")
                        .HasColumnType("text")
                        .HasColumnName("side");

                    b.HasKey("LinkId", "WordId", "Side")
                        .HasName("pk_link_word");

                    b.HasIndex("WordId")
                        .HasDatabaseName("ix_link_word_word_id");

                    b.ToTable("link_word", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.StrongEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Definition")
                        .HasColumnType("text")
                        .HasColumnName("definition");

                    b.Property<string>("Derivation")
                        .HasColumnType("text")
                        .HasColumnName("derivation");

                    b.Property<string>("DetailedDefinition")
                        .HasColumnType("text")
                        .HasColumnName("detailed_definition");

                    b.Property<string>("KjvDefinition")
                        .HasColumnType("text")
                        .HasColumnName("kjv_definition");

                    b.Property<string>("Lemma")
                        .HasColumnType("text")
                        .HasColumnName("lemma");

                    b.Property<string>("Morphology")
                        .HasColumnType("text")
                        .HasColumnName("morphology");

                    b.Property<string>("Pronunciation")
                        .HasColumnType("text")
                        .HasColumnName("pronunciation");

                    b.Property<string>("SeeAlso")
                        .HasColumnType("text")
                        .HasColumnName("see_also");

                    b.Property<string>("SourceLanguage")
                        .HasColumnType("text")
                        .HasColumnName("source_language");

                    b.Property<string>("StrongNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strong_number");

                    b.Property<string>("Transliteration")
                        .HasColumnType("text")
                        .HasColumnName("transliteration");

                    b.Property<string>("TwotReference")
                        .HasColumnType("text")
                        .HasColumnName("twot_reference");

                    b.HasKey("Id")
                        .HasName("pk_strong_entry");

                    b.HasIndex("StrongNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_strong_entry_strong_number");

                    b.ToTable("strong_entry", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.Text", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Licence")
                        .HasColumnType("text")
                        .HasColumnName("licence");

                    b.Property<string>("LicenceUrl")
                        .HasColumnType("text")
                        .HasColumnName("licence_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameNative")
                        .HasColumnType("text")
                        .HasColumnName("name_native");

                    b.Property<int?>("PublishedYear")
                        .HasColumnType("integer")
                        .HasColumnName("published_year");

                    b.Property<string>("Redistribution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("redistribution");

                    b.Property<string>("RightsHolder")
                        .HasColumnType("text")
                        .HasColumnName("rights_holder");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("TextualFamily")
                        .HasColumnType("text")
                        .HasColumnName("textual_family");

                    b.Property<string>("Versification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("versification");

                    b.HasKey("Id")
                        .HasName("pk_text");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_text_slug");

                    b.ToTable("text", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.TextRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FromTextId")
                        .HasColumnType("integer")
                        .HasColumnName("from_text_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relation");

                    b.Property<string>("Scope")
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<int>("ToTextId")
                        .HasColumnType("integer")
                        .HasColumnName("to_text_id");

                    b.HasKey("Id")
                        .HasName("pk_text_relation");

                    b.HasIndex("ToTextId")
                        .HasDatabaseName("ix_text_relation_to_text_id");

                    b.HasIndex("FromTextId", "ToTextId")
                        .HasDatabaseName("ix_text_relation_from_text_id_to_text_id");

                    b.ToTable("text_relation", null, t =>
                        {
                            t.HasCheckConstraint("ck_text_relation_distinct_texts", "\"from_text_id\" <> \"to_text_id\"");
                        });
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.VerificationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Broken")
                        .HasColumnType("integer")
                        .HasColumnName("broken");

                    b.Property<JsonDocument>("Measures")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("measures");

                    b.Property<DateTimeOffset>("RanAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ran_at");

                    b.Property<double>("Rendered")
                        .HasColumnType("double precision")
                        .HasColumnName("rendered");

                    b.HasKey("Id")
                        .HasName("pk_verification_run");

                    b.ToTable("verification_run", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.Verse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer")
                        .HasColumnName("chapter_id");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("chapter_number");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("TextId")
                        .HasColumnType("integer")
                        .HasColumnName("text_id");

                    b.HasKey("Id")
                        .HasName("pk_verse");

                    b.HasIndex("BookId")
                        .HasDatabaseName("ix_verse_book_id");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("ix_verse_chapter_id");

                    b.HasIndex("TextId", "BookId", "ChapterNumber", "Number", "Label")
                        .IsUnique()
                        .HasDatabaseName("ix_verse_text_id_book_id_chapter_number_number_label");

                    b.ToTable("verse", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.VerseLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<int>("FromTextId")
                        .HasColumnType("integer")
                        .HasColumnName("from_text_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relation");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<int>("ToTextId")
                        .HasColumnType("integer")
                        .HasColumnName("to_text_id");

                    b.HasKey("Id")
                        .HasName("pk_verse_link");

                    b.HasIndex("ToTextId")
                        .HasDatabaseName("ix_verse_link_to_text_id");

                    b.HasIndex("FromTextId", "ToTextId")
                        .HasDatabaseName("ix_verse_link_from_text_id_to_text_id");

                    b.ToTable("verse_link", null, t =>
                        {
                            t.HasCheckConstraint("ck_verse_link_confidence_range", "\"confidence\" IS NULL OR (\"confidence\" >= 0 AND \"confidence\" <= 1)");

                            t.HasCheckConstraint("ck_verse_link_inferred_carries_confidence", "\"method\" IN ('stated-by-source', 'manual') OR \"confidence\" IS NOT NULL");

                            t.HasCheckConstraint("ck_verse_link_source_not_empty", "length(btrim(\"source\")) > 0");

                            t.HasCheckConstraint("ck_verse_link_stated_carries_no_confidence", "\"method\" <> 'stated-by-source' OR \"confidence\" IS NULL");
                        });
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.VerseLinkVerse", b =>
                {
                    b.Property<int>("VerseLinkId")
                        .HasColumnType("integer")
                        .HasColumnName("verse_link_id");

                    b.Property<int>("VerseId")
                        .HasColumnType("integer")
                        .HasColumnName("verse_id");

                    b.Property<string>("Side")
                        .HasColumnType("text")
                        .HasColumnName("side");

                    b.HasKey("VerseLinkId", "VerseId", "Side")
                        .HasName("pk_verse_link_verse");

                    b.HasIndex("VerseId")
                        .HasDatabaseName("ix_verse_link_verse_verse_id");

                    b.ToTable("verse_link_verse", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.VerseReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CanonicalBook")
                        .HasColumnType("integer")
                        .HasColumnName("canonical_book");

                    b.Property<int>("CanonicalChapter")
                        .HasColumnType("integer")
                        .HasColumnName("canonical_chapter");

                    b.Property<int>("CanonicalVerse")
                        .HasColumnType("integer")
                        .HasColumnName("canonical_verse");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<int>("VerseId")
                        .HasColumnType("integer")
                        .HasColumnName("verse_id");

                    b.HasKey("Id")
                        .HasName("pk_verse_reference");

                    b.HasIndex("VerseId")
                        .IsUnique()
                        .HasDatabaseName("ix_verse_reference_one_primary_per_verse")
                        .HasFilter("\"is_primary\"");

                    b.HasIndex("CanonicalBook", "CanonicalChapter", "CanonicalVerse")
                        .HasDatabaseName("ix_verse_reference_canonical_book_canonical_chapter_canonical_");

                    b.ToTable("verse_reference", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.Word", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Gloss")
                        .HasColumnType("text")
                        .HasColumnName("gloss");

                    b.Property<string>("Lemma")
                        .HasColumnType("text")
                        .HasColumnName("lemma");

                    b.Property<JsonDocument>("Morphology")
                        .HasColumnType("jsonb")
                        .HasColumnName("morphology");

                    b.Property<string>("NormalisedText")
                        .HasColumnType("text")
                        .HasColumnName("normalised_text");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("StrongNumber")
                        .HasColumnType("text")
                        .HasColumnName("strong_number");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("TextId")
                        .HasColumnType("integer")
                        .HasColumnName("text_id");

                    b.Property<string>("Trailer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trailer");

                    b.Property<int>("VerseId")
                        .HasColumnType("integer")
                        .HasColumnName("verse_id");

                    b.HasKey("Id")
                        .HasName("pk_word");

                    b.HasIndex("StrongNumber")
                        .HasDatabaseName("ix_word_strong_number");

                    b.HasIndex("TextId", "StrongNumber")
                        .HasDatabaseName("ix_word_text_id_strong_number");

                    b.HasIndex("VerseId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_word_verse_id_position");

                    b.ToTable("word", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.WordGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<JsonDocument>("Features")
                        .HasColumnType("jsonb")
                        .HasColumnName("features");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("TextId")
                        .HasColumnType("integer")
                        .HasColumnName("text_id");

                    b.HasKey("Id")
                        .HasName("pk_word_group");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_word_group_parent_id");

                    b.HasIndex("TextId", "Kind")
                        .HasDatabaseName("ix_word_group_text_id_kind");

                    b.ToTable("word_group", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.WordGroupWord", b =>
                {
                    b.Property<long>("WordGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("word_group_id");

                    b.Property<long>("WordId")
                        .HasColumnType("bigint")
                        .HasColumnName("word_id");

                    b.HasKey("WordGroupId", "WordId")
                        .HasName("pk_word_group_word");

                    b.HasIndex("WordId")
                        .HasDatabaseName("ix_word_group_word_word_id");

                    b.ToTable("word_group_word", (string)null);
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.Book", b =>
                {
                    b.HasOne("Essenthos.Core.Database.Entities.Text", "Text")
                        .WithMany("Books")
                        .HasForeignKey("TextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_text_text_id");

                    b.Navigation("Text");
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.Chapter", b =>
                {
                    b.HasOne("Essenthos.Core.Database.Entities.Book", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chapter_book_book_id");

                    b.HasOne("Essenthos.Core.Database.Entities.Text", "Text")
                        .WithMany()
                        .HasForeignKey("TextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chapter_text_text_id");

                    b.Navigation("Book");

                    b.Navigation("Text");
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.Link", b =>
                {
                    b.HasOne("Essenthos.Core.Database.Entities.Text", "FromText")
                        .WithMany()
                        .HasForeignKey("FromTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_link_text_from_text_id");

                    b.HasOne("Essenthos.Core.Database.Entities.Text", "ToText")
                        .WithMany()
                        .HasForeignKey("ToTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_link_text_to_text_id");

                    b.Navigation("FromText");

                    b.Navigation("ToText");
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.LinkWord", b =>
                {
                    b.HasOne("Essenthos.Core.Database.Entities.Link", "Link")
                        .WithMany("Words")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_link_word_links_link_id");

                    b.HasOne("Essenthos.Core.Database.Entities.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_link_word_word_word_id");

                    b.Navigation("Link");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.TextRelation", b =>
                {
                    b.HasOne("Essenthos.Core.Database.Entities.Text", "FromText")
                        .WithMany()
                        .HasForeignKey("FromTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_text_relation_text_from_text_id");

                    b.HasOne("Essenthos.Core.Database.Entities.Text", "ToText")
                        .WithMany()
                        .HasForeignKey("ToTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_text_relation_text_to_text_id");

                    b.Navigation("FromText");

                    b.Navigation("ToText");
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.Verse", b =>
                {
                    b.HasOne("Essenthos.Core.Database.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verse_book_book_id");

                    b.HasOne("Essenthos.Core.Database.Entities.Chapter", "Chapter")
                        .WithMany("Verses")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verse_chapter_chapter_id");

                    b.HasOne("Essenthos.Core.Database.Entities.Text", "Text")
                        .WithMany()
                        .HasForeignKey("TextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verse_text_text_id");

                    b.Navigation("Book");

                    b.Navigation("Chapter");

                    b.Navigation("Text");
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.VerseLink", b =>
                {
                    b.HasOne("Essenthos.Core.Database.Entities.Text", "FromText")
                        .WithMany()
                        .HasForeignKey("FromTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verse_link_text_from_text_id");

                    b.HasOne("Essenthos.Core.Database.Entities.Text", "ToText")
                        .WithMany()
                        .HasForeignKey("ToTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verse_link_text_to_text_id");

                    b.Navigation("FromText");

                    b.Navigation("ToText");
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.VerseLinkVerse", b =>
                {
                    b.HasOne("Essenthos.Core.Database.Entities.Verse", "Verse")
                        .WithMany()
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verse_link_verse_verse_verse_id");

                    b.HasOne("Essenthos.Core.Database.Entities.VerseLink", "VerseLink")
                        .WithMany("Verses")
                        .HasForeignKey("VerseLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verse_link_verse_verse_links_verse_link_id");

                    b.Navigation("Verse");

                    b.Navigation("VerseLink");
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.VerseReference", b =>
                {
                    b.HasOne("Essenthos.Core.Database.Entities.Verse", "Verse")
                        .WithMany("References")
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verse_reference_verse_verse_id");

                    b.Navigation("Verse");
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.Word", b =>
                {
                    b.HasOne("Essenthos.Core.Database.Entities.Text", "Text")
                        .WithMany()
                        .HasForeignKey("TextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_word_text_text_id");

                    b.HasOne("Essenthos.Core.Database.Entities.Verse", "Verse")
                        .WithMany("Words")
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_word_verse_verse_id");

                    b.Navigation("Text");

                    b.Navigation("Verse");
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.WordGroup", b =>
                {
                    b.HasOne("Essenthos.Core.Database.Entities.WordGroup", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_word_group_word_group_parent_id");

                    b.HasOne("Essenthos.Core.Database.Entities.Text", "Text")
                        .WithMany()
                        .HasForeignKey("TextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_word_group_text_text_id");

                    b.Navigation("Parent");

                    b.Navigation("Text");
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.WordGroupWord", b =>
                {
                    b.HasOne("Essenthos.Core.Database.Entities.WordGroup", "WordGroup")
                        .WithMany("Words")
                        .HasForeignKey("WordGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_word_group_word_word_group_word_group_id");

                    b.HasOne("Essenthos.Core.Database.Entities.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_word_group_word_word_word_id");

                    b.Navigation("Word");

                    b.Navigation("WordGroup");
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.Book", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.Chapter", b =>
                {
                    b.Navigation("Verses");
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.Link", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.Text", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.Verse", b =>
                {
                    b.Navigation("References");

                    b.Navigation("Words");
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.VerseLink", b =>
                {
                    b.Navigation("Verses");
                });

            modelBuilder.Entity("Essenthos.Core.Database.Entities.WordGroup", b =>
                {
                    b.Navigation("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
